# Code generated by codegen/generate.py; DO NOT EDIT.

"""Live integration tests for image generation. Skipped when API keys are unset."""

from __future__ import annotations

import os

import pytest

import llmkit
from llmkit import ImageRequest, generate_image


def test_integration_image_google_gemini_3_pro_image_preview() -> None:
    key = os.getenv("GOOGLE_API_KEY")
    if not key:
        pytest.skip("GOOGLE_API_KEY not set")
    if not os.getenv("LLMKIT_RUN_SLOW_IMAGE"):
        pytest.skip("LLMKIT_RUN_SLOW_IMAGE not set; skipping gemini-3-pro-image-preview smoke")
    resp = generate_image(
        llmkit.Provider(name="google", api_key=key),
        ImageRequest(
            prompt="A simple red circle on a white background.",
            model="gemini-3-pro-image-preview",
        ),
        aspect_ratio="1:1",
        image_size="1K",
    )
    assert len(resp.images) > 0
    assert len(resp.images[0].data) > 0
    assert resp.tokens.output > 0, "image-output tokens should land in candidatesTokenCount"


def test_integration_image_google_gemini_3_1_flash_image_preview() -> None:
    key = os.getenv("GOOGLE_API_KEY")
    if not key:
        pytest.skip("GOOGLE_API_KEY not set")
    resp = generate_image(
        llmkit.Provider(name="google", api_key=key),
        ImageRequest(
            prompt="A simple red circle on a white background.",
            model="gemini-3.1-flash-image-preview",
        ),
        aspect_ratio="1:1",
        image_size="1K",
    )
    assert len(resp.images) > 0
    assert len(resp.images[0].data) > 0
    assert resp.tokens.output > 0, "image-output tokens should land in candidatesTokenCount"

