# Code generated by codegen/generate.py; DO NOT EDIT.

"""Integration smoke tests against live provider APIs."""

import asyncio
import os

import pytest

from llmkit.builders import new_client


def test_integration_ai21() -> None:
    key = os.getenv("AI21_API_KEY")
    if not key:
        pytest.skip("AI21_API_KEY not set")
    c = new_client("ai21", key)
    resp = asyncio.run(
        c.text.system("Reply with only the word pong").prompt("ping")
    )
    assert resp.text != "", "empty response text"
    assert resp.usage.input > 0, "no input tokens reported"


def test_integration_ai21_stream() -> None:
    key = os.getenv("AI21_API_KEY")
    if not key:
        pytest.skip("AI21_API_KEY not set")
    c = new_client("ai21", key)

    async def _run() -> list[str]:
        chunks: list[str] = []
        async for chunk in c.text.system("Reply with only the word pong").stream("ping"):
            chunks.append(chunk)
        return chunks

    chunks = asyncio.run(_run())
    assert chunks, "no chunks received"
    assert "".join(chunks) != "", "empty stream output"


def test_integration_anthropic() -> None:
    key = os.getenv("ANTHROPIC_API_KEY")
    if not key:
        pytest.skip("ANTHROPIC_API_KEY not set")
    c = new_client("anthropic", key)
    resp = asyncio.run(
        c.text.system("Reply with only the word pong").prompt("ping")
    )
    assert resp.text != "", "empty response text"
    assert resp.usage.input > 0, "no input tokens reported"


def test_integration_anthropic_stream() -> None:
    key = os.getenv("ANTHROPIC_API_KEY")
    if not key:
        pytest.skip("ANTHROPIC_API_KEY not set")
    c = new_client("anthropic", key)

    async def _run() -> list[str]:
        chunks: list[str] = []
        async for chunk in c.text.system("Reply with only the word pong").stream("ping"):
            chunks.append(chunk)
        return chunks

    chunks = asyncio.run(_run())
    assert chunks, "no chunks received"
    assert "".join(chunks) != "", "empty stream output"


def test_integration_cerebras() -> None:
    key = os.getenv("CEREBRAS_API_KEY")
    if not key:
        pytest.skip("CEREBRAS_API_KEY not set")
    c = new_client("cerebras", key)
    resp = asyncio.run(
        c.text.system("Reply with only the word pong").prompt("ping")
    )
    assert resp.text != "", "empty response text"
    assert resp.usage.input > 0, "no input tokens reported"


def test_integration_cerebras_stream() -> None:
    key = os.getenv("CEREBRAS_API_KEY")
    if not key:
        pytest.skip("CEREBRAS_API_KEY not set")
    c = new_client("cerebras", key)

    async def _run() -> list[str]:
        chunks: list[str] = []
        async for chunk in c.text.system("Reply with only the word pong").stream("ping"):
            chunks.append(chunk)
        return chunks

    chunks = asyncio.run(_run())
    assert chunks, "no chunks received"
    assert "".join(chunks) != "", "empty stream output"


def test_integration_cohere() -> None:
    key = os.getenv("COHERE_API_KEY")
    if not key:
        pytest.skip("COHERE_API_KEY not set")
    c = new_client("cohere", key)
    resp = asyncio.run(
        c.text.system("Reply with only the word pong").prompt("ping")
    )
    assert resp.text != "", "empty response text"
    assert resp.usage.input > 0, "no input tokens reported"


def test_integration_cohere_stream() -> None:
    key = os.getenv("COHERE_API_KEY")
    if not key:
        pytest.skip("COHERE_API_KEY not set")
    c = new_client("cohere", key)

    async def _run() -> list[str]:
        chunks: list[str] = []
        async for chunk in c.text.system("Reply with only the word pong").stream("ping"):
            chunks.append(chunk)
        return chunks

    chunks = asyncio.run(_run())
    assert chunks, "no chunks received"
    assert "".join(chunks) != "", "empty stream output"


def test_integration_deepseek() -> None:
    key = os.getenv("DEEPSEEK_API_KEY")
    if not key:
        pytest.skip("DEEPSEEK_API_KEY not set")
    c = new_client("deepseek", key)
    resp = asyncio.run(
        c.text.system("Reply with only the word pong").prompt("ping")
    )
    assert resp.text != "", "empty response text"
    assert resp.usage.input > 0, "no input tokens reported"


def test_integration_deepseek_stream() -> None:
    key = os.getenv("DEEPSEEK_API_KEY")
    if not key:
        pytest.skip("DEEPSEEK_API_KEY not set")
    c = new_client("deepseek", key)

    async def _run() -> list[str]:
        chunks: list[str] = []
        async for chunk in c.text.system("Reply with only the word pong").stream("ping"):
            chunks.append(chunk)
        return chunks

    chunks = asyncio.run(_run())
    assert chunks, "no chunks received"
    assert "".join(chunks) != "", "empty stream output"


def test_integration_doubao() -> None:
    key = os.getenv("ARK_API_KEY")
    if not key:
        pytest.skip("ARK_API_KEY not set")
    c = new_client("doubao", key)
    resp = asyncio.run(
        c.text.system("Reply with only the word pong").prompt("ping")
    )
    assert resp.text != "", "empty response text"
    assert resp.usage.input > 0, "no input tokens reported"


def test_integration_doubao_stream() -> None:
    key = os.getenv("ARK_API_KEY")
    if not key:
        pytest.skip("ARK_API_KEY not set")
    c = new_client("doubao", key)

    async def _run() -> list[str]:
        chunks: list[str] = []
        async for chunk in c.text.system("Reply with only the word pong").stream("ping"):
            chunks.append(chunk)
        return chunks

    chunks = asyncio.run(_run())
    assert chunks, "no chunks received"
    assert "".join(chunks) != "", "empty stream output"


def test_integration_ernie() -> None:
    key = os.getenv("QIANFAN_API_KEY")
    if not key:
        pytest.skip("QIANFAN_API_KEY not set")
    c = new_client("ernie", key)
    resp = asyncio.run(
        c.text.system("Reply with only the word pong").prompt("ping")
    )
    assert resp.text != "", "empty response text"
    assert resp.usage.input > 0, "no input tokens reported"


def test_integration_ernie_stream() -> None:
    key = os.getenv("QIANFAN_API_KEY")
    if not key:
        pytest.skip("QIANFAN_API_KEY not set")
    c = new_client("ernie", key)

    async def _run() -> list[str]:
        chunks: list[str] = []
        async for chunk in c.text.system("Reply with only the word pong").stream("ping"):
            chunks.append(chunk)
        return chunks

    chunks = asyncio.run(_run())
    assert chunks, "no chunks received"
    assert "".join(chunks) != "", "empty stream output"


def test_integration_fireworks() -> None:
    key = os.getenv("FIREWORKS_API_KEY")
    if not key:
        pytest.skip("FIREWORKS_API_KEY not set")
    c = new_client("fireworks", key)
    resp = asyncio.run(
        c.text.system("Reply with only the word pong").prompt("ping")
    )
    assert resp.text != "", "empty response text"
    assert resp.usage.input > 0, "no input tokens reported"


def test_integration_fireworks_stream() -> None:
    key = os.getenv("FIREWORKS_API_KEY")
    if not key:
        pytest.skip("FIREWORKS_API_KEY not set")
    c = new_client("fireworks", key)

    async def _run() -> list[str]:
        chunks: list[str] = []
        async for chunk in c.text.system("Reply with only the word pong").stream("ping"):
            chunks.append(chunk)
        return chunks

    chunks = asyncio.run(_run())
    assert chunks, "no chunks received"
    assert "".join(chunks) != "", "empty stream output"


def test_integration_google() -> None:
    key = os.getenv("GOOGLE_API_KEY")
    if not key:
        pytest.skip("GOOGLE_API_KEY not set")
    c = new_client("google", key)
    resp = asyncio.run(
        c.text.system("Reply with only the word pong").prompt("ping")
    )
    assert resp.text != "", "empty response text"
    assert resp.usage.input > 0, "no input tokens reported"


def test_integration_google_stream() -> None:
    key = os.getenv("GOOGLE_API_KEY")
    if not key:
        pytest.skip("GOOGLE_API_KEY not set")
    c = new_client("google", key)

    async def _run() -> list[str]:
        chunks: list[str] = []
        async for chunk in c.text.system("Reply with only the word pong").stream("ping"):
            chunks.append(chunk)
        return chunks

    chunks = asyncio.run(_run())
    assert chunks, "no chunks received"
    assert "".join(chunks) != "", "empty stream output"


def test_integration_grok() -> None:
    key = os.getenv("XAI_API_KEY")
    if not key:
        pytest.skip("XAI_API_KEY not set")
    c = new_client("grok", key)
    resp = asyncio.run(
        c.text.system("Reply with only the word pong").prompt("ping")
    )
    assert resp.text != "", "empty response text"
    assert resp.usage.input > 0, "no input tokens reported"


def test_integration_grok_stream() -> None:
    key = os.getenv("XAI_API_KEY")
    if not key:
        pytest.skip("XAI_API_KEY not set")
    c = new_client("grok", key)

    async def _run() -> list[str]:
        chunks: list[str] = []
        async for chunk in c.text.system("Reply with only the word pong").stream("ping"):
            chunks.append(chunk)
        return chunks

    chunks = asyncio.run(_run())
    assert chunks, "no chunks received"
    assert "".join(chunks) != "", "empty stream output"


def test_integration_groq() -> None:
    key = os.getenv("GROQ_API_KEY")
    if not key:
        pytest.skip("GROQ_API_KEY not set")
    c = new_client("groq", key)
    resp = asyncio.run(
        c.text.system("Reply with only the word pong").prompt("ping")
    )
    assert resp.text != "", "empty response text"
    assert resp.usage.input > 0, "no input tokens reported"


def test_integration_groq_stream() -> None:
    key = os.getenv("GROQ_API_KEY")
    if not key:
        pytest.skip("GROQ_API_KEY not set")
    c = new_client("groq", key)

    async def _run() -> list[str]:
        chunks: list[str] = []
        async for chunk in c.text.system("Reply with only the word pong").stream("ping"):
            chunks.append(chunk)
        return chunks

    chunks = asyncio.run(_run())
    assert chunks, "no chunks received"
    assert "".join(chunks) != "", "empty stream output"


def test_integration_jan() -> None:
    key = os.getenv("JAN_API_KEY")
    if not key:
        pytest.skip("JAN_API_KEY not set")
    c = new_client("jan", key)
    resp = asyncio.run(
        c.text.system("Reply with only the word pong").prompt("ping")
    )
    assert resp.text != "", "empty response text"
    assert resp.usage.input > 0, "no input tokens reported"


def test_integration_jan_stream() -> None:
    key = os.getenv("JAN_API_KEY")
    if not key:
        pytest.skip("JAN_API_KEY not set")
    c = new_client("jan", key)

    async def _run() -> list[str]:
        chunks: list[str] = []
        async for chunk in c.text.system("Reply with only the word pong").stream("ping"):
            chunks.append(chunk)
        return chunks

    chunks = asyncio.run(_run())
    assert chunks, "no chunks received"
    assert "".join(chunks) != "", "empty stream output"


def test_integration_llamacpp() -> None:
    key = os.getenv("LLAMACPP_API_KEY")
    if not key:
        pytest.skip("LLAMACPP_API_KEY not set")
    c = new_client("llamacpp", key)
    resp = asyncio.run(
        c.text.system("Reply with only the word pong").prompt("ping")
    )
    assert resp.text != "", "empty response text"
    assert resp.usage.input > 0, "no input tokens reported"


def test_integration_llamacpp_stream() -> None:
    key = os.getenv("LLAMACPP_API_KEY")
    if not key:
        pytest.skip("LLAMACPP_API_KEY not set")
    c = new_client("llamacpp", key)

    async def _run() -> list[str]:
        chunks: list[str] = []
        async for chunk in c.text.system("Reply with only the word pong").stream("ping"):
            chunks.append(chunk)
        return chunks

    chunks = asyncio.run(_run())
    assert chunks, "no chunks received"
    assert "".join(chunks) != "", "empty stream output"


def test_integration_minimax() -> None:
    key = os.getenv("MINIMAX_API_KEY")
    if not key:
        pytest.skip("MINIMAX_API_KEY not set")
    c = new_client("minimax", key)
    resp = asyncio.run(
        c.text.system("Reply with only the word pong").prompt("ping")
    )
    assert resp.text != "", "empty response text"
    assert resp.usage.input > 0, "no input tokens reported"


def test_integration_minimax_stream() -> None:
    key = os.getenv("MINIMAX_API_KEY")
    if not key:
        pytest.skip("MINIMAX_API_KEY not set")
    c = new_client("minimax", key)

    async def _run() -> list[str]:
        chunks: list[str] = []
        async for chunk in c.text.system("Reply with only the word pong").stream("ping"):
            chunks.append(chunk)
        return chunks

    chunks = asyncio.run(_run())
    assert chunks, "no chunks received"
    assert "".join(chunks) != "", "empty stream output"


def test_integration_mistral() -> None:
    key = os.getenv("MISTRAL_API_KEY")
    if not key:
        pytest.skip("MISTRAL_API_KEY not set")
    c = new_client("mistral", key)
    resp = asyncio.run(
        c.text.system("Reply with only the word pong").prompt("ping")
    )
    assert resp.text != "", "empty response text"
    assert resp.usage.input > 0, "no input tokens reported"


def test_integration_mistral_stream() -> None:
    key = os.getenv("MISTRAL_API_KEY")
    if not key:
        pytest.skip("MISTRAL_API_KEY not set")
    c = new_client("mistral", key)

    async def _run() -> list[str]:
        chunks: list[str] = []
        async for chunk in c.text.system("Reply with only the word pong").stream("ping"):
            chunks.append(chunk)
        return chunks

    chunks = asyncio.run(_run())
    assert chunks, "no chunks received"
    assert "".join(chunks) != "", "empty stream output"


def test_integration_moonshot() -> None:
    key = os.getenv("MOONSHOT_API_KEY")
    if not key:
        pytest.skip("MOONSHOT_API_KEY not set")
    c = new_client("moonshot", key)
    resp = asyncio.run(
        c.text.system("Reply with only the word pong").prompt("ping")
    )
    assert resp.text != "", "empty response text"
    assert resp.usage.input > 0, "no input tokens reported"


def test_integration_moonshot_stream() -> None:
    key = os.getenv("MOONSHOT_API_KEY")
    if not key:
        pytest.skip("MOONSHOT_API_KEY not set")
    c = new_client("moonshot", key)

    async def _run() -> list[str]:
        chunks: list[str] = []
        async for chunk in c.text.system("Reply with only the word pong").stream("ping"):
            chunks.append(chunk)
        return chunks

    chunks = asyncio.run(_run())
    assert chunks, "no chunks received"
    assert "".join(chunks) != "", "empty stream output"


def test_integration_openai() -> None:
    key = os.getenv("OPENAI_API_KEY")
    if not key:
        pytest.skip("OPENAI_API_KEY not set")
    c = new_client("openai", key)
    resp = asyncio.run(
        c.text.system("Reply with only the word pong").prompt("ping")
    )
    assert resp.text != "", "empty response text"
    assert resp.usage.input > 0, "no input tokens reported"


def test_integration_openai_stream() -> None:
    key = os.getenv("OPENAI_API_KEY")
    if not key:
        pytest.skip("OPENAI_API_KEY not set")
    c = new_client("openai", key)

    async def _run() -> list[str]:
        chunks: list[str] = []
        async for chunk in c.text.system("Reply with only the word pong").stream("ping"):
            chunks.append(chunk)
        return chunks

    chunks = asyncio.run(_run())
    assert chunks, "no chunks received"
    assert "".join(chunks) != "", "empty stream output"


def test_integration_openrouter() -> None:
    key = os.getenv("OPENROUTER_API_KEY")
    if not key:
        pytest.skip("OPENROUTER_API_KEY not set")
    c = new_client("openrouter", key)
    resp = asyncio.run(
        c.text.system("Reply with only the word pong").prompt("ping")
    )
    assert resp.text != "", "empty response text"
    assert resp.usage.input > 0, "no input tokens reported"


def test_integration_openrouter_stream() -> None:
    key = os.getenv("OPENROUTER_API_KEY")
    if not key:
        pytest.skip("OPENROUTER_API_KEY not set")
    c = new_client("openrouter", key)

    async def _run() -> list[str]:
        chunks: list[str] = []
        async for chunk in c.text.system("Reply with only the word pong").stream("ping"):
            chunks.append(chunk)
        return chunks

    chunks = asyncio.run(_run())
    assert chunks, "no chunks received"
    assert "".join(chunks) != "", "empty stream output"


def test_integration_perplexity() -> None:
    key = os.getenv("PERPLEXITY_API_KEY")
    if not key:
        pytest.skip("PERPLEXITY_API_KEY not set")
    c = new_client("perplexity", key)
    resp = asyncio.run(
        c.text.system("Reply with only the word pong").prompt("ping")
    )
    assert resp.text != "", "empty response text"
    assert resp.usage.input > 0, "no input tokens reported"


def test_integration_perplexity_stream() -> None:
    key = os.getenv("PERPLEXITY_API_KEY")
    if not key:
        pytest.skip("PERPLEXITY_API_KEY not set")
    c = new_client("perplexity", key)

    async def _run() -> list[str]:
        chunks: list[str] = []
        async for chunk in c.text.system("Reply with only the word pong").stream("ping"):
            chunks.append(chunk)
        return chunks

    chunks = asyncio.run(_run())
    assert chunks, "no chunks received"
    assert "".join(chunks) != "", "empty stream output"


def test_integration_qwen() -> None:
    key = os.getenv("DASHSCOPE_API_KEY")
    if not key:
        pytest.skip("DASHSCOPE_API_KEY not set")
    c = new_client("qwen", key)
    resp = asyncio.run(
        c.text.system("Reply with only the word pong").prompt("ping")
    )
    assert resp.text != "", "empty response text"
    assert resp.usage.input > 0, "no input tokens reported"


def test_integration_qwen_stream() -> None:
    key = os.getenv("DASHSCOPE_API_KEY")
    if not key:
        pytest.skip("DASHSCOPE_API_KEY not set")
    c = new_client("qwen", key)

    async def _run() -> list[str]:
        chunks: list[str] = []
        async for chunk in c.text.system("Reply with only the word pong").stream("ping"):
            chunks.append(chunk)
        return chunks

    chunks = asyncio.run(_run())
    assert chunks, "no chunks received"
    assert "".join(chunks) != "", "empty stream output"


def test_integration_sambanova() -> None:
    key = os.getenv("SAMBANOVA_API_KEY")
    if not key:
        pytest.skip("SAMBANOVA_API_KEY not set")
    c = new_client("sambanova", key)
    resp = asyncio.run(
        c.text.system("Reply with only the word pong").prompt("ping")
    )
    assert resp.text != "", "empty response text"
    assert resp.usage.input > 0, "no input tokens reported"


def test_integration_sambanova_stream() -> None:
    key = os.getenv("SAMBANOVA_API_KEY")
    if not key:
        pytest.skip("SAMBANOVA_API_KEY not set")
    c = new_client("sambanova", key)

    async def _run() -> list[str]:
        chunks: list[str] = []
        async for chunk in c.text.system("Reply with only the word pong").stream("ping"):
            chunks.append(chunk)
        return chunks

    chunks = asyncio.run(_run())
    assert chunks, "no chunks received"
    assert "".join(chunks) != "", "empty stream output"


def test_integration_together() -> None:
    key = os.getenv("TOGETHER_API_KEY")
    if not key:
        pytest.skip("TOGETHER_API_KEY not set")
    c = new_client("together", key)
    resp = asyncio.run(
        c.text.system("Reply with only the word pong").prompt("ping")
    )
    assert resp.text != "", "empty response text"
    assert resp.usage.input > 0, "no input tokens reported"


def test_integration_together_stream() -> None:
    key = os.getenv("TOGETHER_API_KEY")
    if not key:
        pytest.skip("TOGETHER_API_KEY not set")
    c = new_client("together", key)

    async def _run() -> list[str]:
        chunks: list[str] = []
        async for chunk in c.text.system("Reply with only the word pong").stream("ping"):
            chunks.append(chunk)
        return chunks

    chunks = asyncio.run(_run())
    assert chunks, "no chunks received"
    assert "".join(chunks) != "", "empty stream output"


def test_integration_vertex() -> None:
    key = os.getenv("VERTEX_BEARER_TOKEN")
    if not key:
        pytest.skip("VERTEX_BEARER_TOKEN not set")
    c = new_client("vertex", key)
    resp = asyncio.run(
        c.text.system("Reply with only the word pong").prompt("ping")
    )
    assert resp.text != "", "empty response text"
    assert resp.usage.input > 0, "no input tokens reported"


def test_integration_yi() -> None:
    key = os.getenv("YI_API_KEY")
    if not key:
        pytest.skip("YI_API_KEY not set")
    c = new_client("yi", key)
    resp = asyncio.run(
        c.text.system("Reply with only the word pong").prompt("ping")
    )
    assert resp.text != "", "empty response text"
    assert resp.usage.input > 0, "no input tokens reported"


def test_integration_yi_stream() -> None:
    key = os.getenv("YI_API_KEY")
    if not key:
        pytest.skip("YI_API_KEY not set")
    c = new_client("yi", key)

    async def _run() -> list[str]:
        chunks: list[str] = []
        async for chunk in c.text.system("Reply with only the word pong").stream("ping"):
            chunks.append(chunk)
        return chunks

    chunks = asyncio.run(_run())
    assert chunks, "no chunks received"
    assert "".join(chunks) != "", "empty stream output"


def test_integration_zhipu() -> None:
    key = os.getenv("ZHIPU_API_KEY")
    if not key:
        pytest.skip("ZHIPU_API_KEY not set")
    c = new_client("zhipu", key)
    resp = asyncio.run(
        c.text.system("Reply with only the word pong").prompt("ping")
    )
    assert resp.text != "", "empty response text"
    assert resp.usage.input > 0, "no input tokens reported"


def test_integration_zhipu_stream() -> None:
    key = os.getenv("ZHIPU_API_KEY")
    if not key:
        pytest.skip("ZHIPU_API_KEY not set")
    c = new_client("zhipu", key)

    async def _run() -> list[str]:
        chunks: list[str] = []
        async for chunk in c.text.system("Reply with only the word pong").stream("ping"):
            chunks.append(chunk)
        return chunks

    chunks = asyncio.run(_run())
    assert chunks, "no chunks received"
    assert "".join(chunks) != "", "empty stream output"


def test_integration_anthropic_caching() -> None:
    key = os.getenv("ANTHROPIC_API_KEY")
    if not key:
        pytest.skip("ANTHROPIC_API_KEY not set")
    c = new_client("anthropic", key)
    resp = asyncio.run(
        c.text.system("Reply with only the word pong").caching().prompt("ping")
    )
    assert resp.text != "", "empty response text"
    print(f"cache_read={resp.usage.cache_read} cache_write={resp.usage.cache_write}")


def test_integration_openai_caching() -> None:
    key = os.getenv("OPENAI_API_KEY")
    if not key:
        pytest.skip("OPENAI_API_KEY not set")
    c = new_client("openai", key)
    resp = asyncio.run(
        c.text.system("Reply with only the word pong").caching().prompt("ping")
    )
    assert resp.text != "", "empty response text"
    print(f"cache_read={resp.usage.cache_read} cache_write={resp.usage.cache_write}")

