# Code generated by codegen/generate.py; DO NOT EDIT.

"""Live integration tests for image generation. Skipped when API keys are unset."""

from __future__ import annotations

import asyncio
import os

import pytest

from llmkit.builders import new_client


def test_integration_image_google_gemini_3_pro_image_preview() -> None:
    key = os.getenv("GOOGLE_API_KEY")
    if not key:
        pytest.skip("GOOGLE_API_KEY not set")
    if not os.getenv("LLMKIT_RUN_SLOW_IMAGE"):
        pytest.skip("LLMKIT_RUN_SLOW_IMAGE not set; skipping gemini-3-pro-image-preview smoke")
    c = new_client("google", key)
    resp = asyncio.run(
        c.image
        .model("gemini-3-pro-image-preview")
        .aspect_ratio("1:1")
        .image_size("1K")
        .generate("A simple red circle on a white background.")
    )
    assert len(resp.images) > 0
    assert len(resp.images[0].data) > 0
    assert resp.usage.output > 0, "image-output tokens should land in candidatesTokenCount"


def test_integration_image_google_gemini_3_1_flash_image_preview() -> None:
    key = os.getenv("GOOGLE_API_KEY")
    if not key:
        pytest.skip("GOOGLE_API_KEY not set")
    c = new_client("google", key)
    resp = asyncio.run(
        c.image
        .model("gemini-3.1-flash-image-preview")
        .aspect_ratio("1:1")
        .image_size("1K")
        .generate("A simple red circle on a white background.")
    )
    assert len(resp.images) > 0
    assert len(resp.images[0].data) > 0
    assert resp.usage.output > 0, "image-output tokens should land in candidatesTokenCount"


def test_integration_image_grok_grok_imagine_image_quality() -> None:
    key = os.getenv("XAI_API_KEY")
    if not key:
        pytest.skip("XAI_API_KEY not set")
    c = new_client("grok", key)
    resp = asyncio.run(
        c.image
        .model("grok-imagine-image-quality")
        .aspect_ratio("1:1")
        .generate("A simple red circle on a white background.")
    )
    assert len(resp.images) > 0
    assert len(resp.images[0].data) > 0


def test_integration_image_openai_gpt_image_1() -> None:
    key = os.getenv("OPENAI_API_KEY")
    if not key:
        pytest.skip("OPENAI_API_KEY not set")
    if not os.getenv("LLMKIT_RUN_SLOW_IMAGE"):
        pytest.skip("LLMKIT_RUN_SLOW_IMAGE not set; skipping gpt-image-1 smoke")
    c = new_client("openai", key)
    resp = asyncio.run(
        c.image
        .model("gpt-image-1")
        .generate("A simple red circle on a white background.")
    )
    assert len(resp.images) > 0
    assert len(resp.images[0].data) > 0
    assert resp.usage.output > 0, "image-output tokens should land in candidatesTokenCount"


def test_integration_image_openai_gpt_image_1_mini() -> None:
    key = os.getenv("OPENAI_API_KEY")
    if not key:
        pytest.skip("OPENAI_API_KEY not set")
    if not os.getenv("LLMKIT_RUN_SLOW_IMAGE"):
        pytest.skip("LLMKIT_RUN_SLOW_IMAGE not set; skipping gpt-image-1-mini smoke")
    c = new_client("openai", key)
    resp = asyncio.run(
        c.image
        .model("gpt-image-1-mini")
        .generate("A simple red circle on a white background.")
    )
    assert len(resp.images) > 0
    assert len(resp.images[0].data) > 0
    assert resp.usage.output > 0, "image-output tokens should land in candidatesTokenCount"


def test_integration_image_openai_gpt_image_1_5() -> None:
    key = os.getenv("OPENAI_API_KEY")
    if not key:
        pytest.skip("OPENAI_API_KEY not set")
    if not os.getenv("LLMKIT_RUN_SLOW_IMAGE"):
        pytest.skip("LLMKIT_RUN_SLOW_IMAGE not set; skipping gpt-image-1.5 smoke")
    c = new_client("openai", key)
    resp = asyncio.run(
        c.image
        .model("gpt-image-1.5")
        .generate("A simple red circle on a white background.")
    )
    assert len(resp.images) > 0
    assert len(resp.images[0].data) > 0
    assert resp.usage.output > 0, "image-output tokens should land in candidatesTokenCount"


def test_integration_image_openai_gpt_image_2() -> None:
    key = os.getenv("OPENAI_API_KEY")
    if not key:
        pytest.skip("OPENAI_API_KEY not set")
    c = new_client("openai", key)
    resp = asyncio.run(
        c.image
        .model("gpt-image-2")
        .generate("A simple red circle on a white background.")
    )
    assert len(resp.images) > 0
    assert len(resp.images[0].data) > 0
    assert resp.usage.output > 0, "image-output tokens should land in candidatesTokenCount"


def test_integration_image_vertex_imagen_3_0_fast_generate_001() -> None:
    key = os.getenv("VERTEX_BEARER_TOKEN")
    if not key:
        pytest.skip("VERTEX_BEARER_TOKEN not set")
    c = new_client("vertex", key)
    resp = asyncio.run(
        c.image
        .model("imagen-3.0-fast-generate-001")
        .aspect_ratio("1:1")
        .generate("A simple red circle on a white background.")
    )
    assert len(resp.images) > 0
    assert len(resp.images[0].data) > 0
    assert resp.usage.output > 0, "image-output tokens should land in candidatesTokenCount"


def test_integration_image_vertex_imagen_3_0_generate_002() -> None:
    key = os.getenv("VERTEX_BEARER_TOKEN")
    if not key:
        pytest.skip("VERTEX_BEARER_TOKEN not set")
    c = new_client("vertex", key)
    resp = asyncio.run(
        c.image
        .model("imagen-3.0-generate-002")
        .aspect_ratio("1:1")
        .generate("A simple red circle on a white background.")
    )
    assert len(resp.images) > 0
    assert len(resp.images[0].data) > 0
    assert resp.usage.output > 0, "image-output tokens should land in candidatesTokenCount"


def test_integration_image_vertex_imagen_4_0_generate_preview_06_06() -> None:
    key = os.getenv("VERTEX_BEARER_TOKEN")
    if not key:
        pytest.skip("VERTEX_BEARER_TOKEN not set")
    c = new_client("vertex", key)
    resp = asyncio.run(
        c.image
        .model("imagen-4.0-generate-preview-06-06")
        .aspect_ratio("1:1")
        .generate("A simple red circle on a white background.")
    )
    assert len(resp.images) > 0
    assert len(resp.images[0].data) > 0
    assert resp.usage.output > 0, "image-output tokens should land in candidatesTokenCount"

