# Code generated by codegen/generate.py; DO NOT EDIT.

"""Integration smoke tests against live provider APIs."""

import os

import pytest

import llmkit


def test_integration_ai21() -> None:
    key = os.getenv("AI21_API_KEY")
    if not key:
        pytest.skip("AI21_API_KEY not set")
    resp = llmkit.prompt(
        provider=llmkit.Provider(name="ai21", api_key=key),
        request=llmkit.Request(system="Reply with only the word pong", user="ping"),
    )
    assert resp.text != "", "empty response text"
    assert resp.tokens.input > 0, "no input tokens reported"


def test_integration_ai21_stream() -> None:
    key = os.getenv("AI21_API_KEY")
    if not key:
        pytest.skip("AI21_API_KEY not set")
    chunks: list[str] = []
    resp = llmkit.prompt_stream(
        provider=llmkit.Provider(name="ai21", api_key=key),
        request=llmkit.Request(system="Reply with only the word pong", user="ping"),
        on_chunk=chunks.append,
    )
    assert resp.text != "", "empty response text"
    assert chunks, "no chunks received"


def test_integration_anthropic() -> None:
    key = os.getenv("ANTHROPIC_API_KEY")
    if not key:
        pytest.skip("ANTHROPIC_API_KEY not set")
    resp = llmkit.prompt(
        provider=llmkit.Provider(name="anthropic", api_key=key),
        request=llmkit.Request(system="Reply with only the word pong", user="ping"),
    )
    assert resp.text != "", "empty response text"
    assert resp.tokens.input > 0, "no input tokens reported"


def test_integration_anthropic_stream() -> None:
    key = os.getenv("ANTHROPIC_API_KEY")
    if not key:
        pytest.skip("ANTHROPIC_API_KEY not set")
    chunks: list[str] = []
    resp = llmkit.prompt_stream(
        provider=llmkit.Provider(name="anthropic", api_key=key),
        request=llmkit.Request(system="Reply with only the word pong", user="ping"),
        on_chunk=chunks.append,
    )
    assert resp.text != "", "empty response text"
    assert chunks, "no chunks received"


def test_integration_cerebras() -> None:
    key = os.getenv("CEREBRAS_API_KEY")
    if not key:
        pytest.skip("CEREBRAS_API_KEY not set")
    resp = llmkit.prompt(
        provider=llmkit.Provider(name="cerebras", api_key=key),
        request=llmkit.Request(system="Reply with only the word pong", user="ping"),
    )
    assert resp.text != "", "empty response text"
    assert resp.tokens.input > 0, "no input tokens reported"


def test_integration_cerebras_stream() -> None:
    key = os.getenv("CEREBRAS_API_KEY")
    if not key:
        pytest.skip("CEREBRAS_API_KEY not set")
    chunks: list[str] = []
    resp = llmkit.prompt_stream(
        provider=llmkit.Provider(name="cerebras", api_key=key),
        request=llmkit.Request(system="Reply with only the word pong", user="ping"),
        on_chunk=chunks.append,
    )
    assert resp.text != "", "empty response text"
    assert chunks, "no chunks received"


def test_integration_cohere() -> None:
    key = os.getenv("COHERE_API_KEY")
    if not key:
        pytest.skip("COHERE_API_KEY not set")
    resp = llmkit.prompt(
        provider=llmkit.Provider(name="cohere", api_key=key),
        request=llmkit.Request(system="Reply with only the word pong", user="ping"),
    )
    assert resp.text != "", "empty response text"
    assert resp.tokens.input > 0, "no input tokens reported"


def test_integration_cohere_stream() -> None:
    key = os.getenv("COHERE_API_KEY")
    if not key:
        pytest.skip("COHERE_API_KEY not set")
    chunks: list[str] = []
    resp = llmkit.prompt_stream(
        provider=llmkit.Provider(name="cohere", api_key=key),
        request=llmkit.Request(system="Reply with only the word pong", user="ping"),
        on_chunk=chunks.append,
    )
    assert resp.text != "", "empty response text"
    assert chunks, "no chunks received"


def test_integration_deepseek() -> None:
    key = os.getenv("DEEPSEEK_API_KEY")
    if not key:
        pytest.skip("DEEPSEEK_API_KEY not set")
    resp = llmkit.prompt(
        provider=llmkit.Provider(name="deepseek", api_key=key),
        request=llmkit.Request(system="Reply with only the word pong", user="ping"),
    )
    assert resp.text != "", "empty response text"
    assert resp.tokens.input > 0, "no input tokens reported"


def test_integration_deepseek_stream() -> None:
    key = os.getenv("DEEPSEEK_API_KEY")
    if not key:
        pytest.skip("DEEPSEEK_API_KEY not set")
    chunks: list[str] = []
    resp = llmkit.prompt_stream(
        provider=llmkit.Provider(name="deepseek", api_key=key),
        request=llmkit.Request(system="Reply with only the word pong", user="ping"),
        on_chunk=chunks.append,
    )
    assert resp.text != "", "empty response text"
    assert chunks, "no chunks received"


def test_integration_doubao() -> None:
    key = os.getenv("ARK_API_KEY")
    if not key:
        pytest.skip("ARK_API_KEY not set")
    resp = llmkit.prompt(
        provider=llmkit.Provider(name="doubao", api_key=key),
        request=llmkit.Request(system="Reply with only the word pong", user="ping"),
    )
    assert resp.text != "", "empty response text"
    assert resp.tokens.input > 0, "no input tokens reported"


def test_integration_doubao_stream() -> None:
    key = os.getenv("ARK_API_KEY")
    if not key:
        pytest.skip("ARK_API_KEY not set")
    chunks: list[str] = []
    resp = llmkit.prompt_stream(
        provider=llmkit.Provider(name="doubao", api_key=key),
        request=llmkit.Request(system="Reply with only the word pong", user="ping"),
        on_chunk=chunks.append,
    )
    assert resp.text != "", "empty response text"
    assert chunks, "no chunks received"


def test_integration_ernie() -> None:
    key = os.getenv("QIANFAN_API_KEY")
    if not key:
        pytest.skip("QIANFAN_API_KEY not set")
    resp = llmkit.prompt(
        provider=llmkit.Provider(name="ernie", api_key=key),
        request=llmkit.Request(system="Reply with only the word pong", user="ping"),
    )
    assert resp.text != "", "empty response text"
    assert resp.tokens.input > 0, "no input tokens reported"


def test_integration_ernie_stream() -> None:
    key = os.getenv("QIANFAN_API_KEY")
    if not key:
        pytest.skip("QIANFAN_API_KEY not set")
    chunks: list[str] = []
    resp = llmkit.prompt_stream(
        provider=llmkit.Provider(name="ernie", api_key=key),
        request=llmkit.Request(system="Reply with only the word pong", user="ping"),
        on_chunk=chunks.append,
    )
    assert resp.text != "", "empty response text"
    assert chunks, "no chunks received"


def test_integration_fireworks() -> None:
    key = os.getenv("FIREWORKS_API_KEY")
    if not key:
        pytest.skip("FIREWORKS_API_KEY not set")
    resp = llmkit.prompt(
        provider=llmkit.Provider(name="fireworks", api_key=key),
        request=llmkit.Request(system="Reply with only the word pong", user="ping"),
    )
    assert resp.text != "", "empty response text"
    assert resp.tokens.input > 0, "no input tokens reported"


def test_integration_fireworks_stream() -> None:
    key = os.getenv("FIREWORKS_API_KEY")
    if not key:
        pytest.skip("FIREWORKS_API_KEY not set")
    chunks: list[str] = []
    resp = llmkit.prompt_stream(
        provider=llmkit.Provider(name="fireworks", api_key=key),
        request=llmkit.Request(system="Reply with only the word pong", user="ping"),
        on_chunk=chunks.append,
    )
    assert resp.text != "", "empty response text"
    assert chunks, "no chunks received"


def test_integration_google() -> None:
    key = os.getenv("GOOGLE_API_KEY")
    if not key:
        pytest.skip("GOOGLE_API_KEY not set")
    resp = llmkit.prompt(
        provider=llmkit.Provider(name="google", api_key=key),
        request=llmkit.Request(system="Reply with only the word pong", user="ping"),
    )
    assert resp.text != "", "empty response text"
    assert resp.tokens.input > 0, "no input tokens reported"


def test_integration_google_stream() -> None:
    key = os.getenv("GOOGLE_API_KEY")
    if not key:
        pytest.skip("GOOGLE_API_KEY not set")
    chunks: list[str] = []
    resp = llmkit.prompt_stream(
        provider=llmkit.Provider(name="google", api_key=key),
        request=llmkit.Request(system="Reply with only the word pong", user="ping"),
        on_chunk=chunks.append,
    )
    assert resp.text != "", "empty response text"
    assert chunks, "no chunks received"


def test_integration_grok() -> None:
    key = os.getenv("GROK_API_KEY")
    if not key:
        pytest.skip("GROK_API_KEY not set")
    resp = llmkit.prompt(
        provider=llmkit.Provider(name="grok", api_key=key),
        request=llmkit.Request(system="Reply with only the word pong", user="ping"),
    )
    assert resp.text != "", "empty response text"
    assert resp.tokens.input > 0, "no input tokens reported"


def test_integration_grok_stream() -> None:
    key = os.getenv("GROK_API_KEY")
    if not key:
        pytest.skip("GROK_API_KEY not set")
    chunks: list[str] = []
    resp = llmkit.prompt_stream(
        provider=llmkit.Provider(name="grok", api_key=key),
        request=llmkit.Request(system="Reply with only the word pong", user="ping"),
        on_chunk=chunks.append,
    )
    assert resp.text != "", "empty response text"
    assert chunks, "no chunks received"


def test_integration_groq() -> None:
    key = os.getenv("GROQ_API_KEY")
    if not key:
        pytest.skip("GROQ_API_KEY not set")
    resp = llmkit.prompt(
        provider=llmkit.Provider(name="groq", api_key=key),
        request=llmkit.Request(system="Reply with only the word pong", user="ping"),
    )
    assert resp.text != "", "empty response text"
    assert resp.tokens.input > 0, "no input tokens reported"


def test_integration_groq_stream() -> None:
    key = os.getenv("GROQ_API_KEY")
    if not key:
        pytest.skip("GROQ_API_KEY not set")
    chunks: list[str] = []
    resp = llmkit.prompt_stream(
        provider=llmkit.Provider(name="groq", api_key=key),
        request=llmkit.Request(system="Reply with only the word pong", user="ping"),
        on_chunk=chunks.append,
    )
    assert resp.text != "", "empty response text"
    assert chunks, "no chunks received"


def test_integration_minimax() -> None:
    key = os.getenv("MINIMAX_API_KEY")
    if not key:
        pytest.skip("MINIMAX_API_KEY not set")
    resp = llmkit.prompt(
        provider=llmkit.Provider(name="minimax", api_key=key),
        request=llmkit.Request(system="Reply with only the word pong", user="ping"),
    )
    assert resp.text != "", "empty response text"
    assert resp.tokens.input > 0, "no input tokens reported"


def test_integration_minimax_stream() -> None:
    key = os.getenv("MINIMAX_API_KEY")
    if not key:
        pytest.skip("MINIMAX_API_KEY not set")
    chunks: list[str] = []
    resp = llmkit.prompt_stream(
        provider=llmkit.Provider(name="minimax", api_key=key),
        request=llmkit.Request(system="Reply with only the word pong", user="ping"),
        on_chunk=chunks.append,
    )
    assert resp.text != "", "empty response text"
    assert chunks, "no chunks received"


def test_integration_mistral() -> None:
    key = os.getenv("MISTRAL_API_KEY")
    if not key:
        pytest.skip("MISTRAL_API_KEY not set")
    resp = llmkit.prompt(
        provider=llmkit.Provider(name="mistral", api_key=key),
        request=llmkit.Request(system="Reply with only the word pong", user="ping"),
    )
    assert resp.text != "", "empty response text"
    assert resp.tokens.input > 0, "no input tokens reported"


def test_integration_mistral_stream() -> None:
    key = os.getenv("MISTRAL_API_KEY")
    if not key:
        pytest.skip("MISTRAL_API_KEY not set")
    chunks: list[str] = []
    resp = llmkit.prompt_stream(
        provider=llmkit.Provider(name="mistral", api_key=key),
        request=llmkit.Request(system="Reply with only the word pong", user="ping"),
        on_chunk=chunks.append,
    )
    assert resp.text != "", "empty response text"
    assert chunks, "no chunks received"


def test_integration_moonshot() -> None:
    key = os.getenv("MOONSHOT_API_KEY")
    if not key:
        pytest.skip("MOONSHOT_API_KEY not set")
    resp = llmkit.prompt(
        provider=llmkit.Provider(name="moonshot", api_key=key),
        request=llmkit.Request(system="Reply with only the word pong", user="ping"),
    )
    assert resp.text != "", "empty response text"
    assert resp.tokens.input > 0, "no input tokens reported"


def test_integration_moonshot_stream() -> None:
    key = os.getenv("MOONSHOT_API_KEY")
    if not key:
        pytest.skip("MOONSHOT_API_KEY not set")
    chunks: list[str] = []
    resp = llmkit.prompt_stream(
        provider=llmkit.Provider(name="moonshot", api_key=key),
        request=llmkit.Request(system="Reply with only the word pong", user="ping"),
        on_chunk=chunks.append,
    )
    assert resp.text != "", "empty response text"
    assert chunks, "no chunks received"


def test_integration_openai() -> None:
    key = os.getenv("OPENAI_API_KEY")
    if not key:
        pytest.skip("OPENAI_API_KEY not set")
    resp = llmkit.prompt(
        provider=llmkit.Provider(name="openai", api_key=key),
        request=llmkit.Request(system="Reply with only the word pong", user="ping"),
    )
    assert resp.text != "", "empty response text"
    assert resp.tokens.input > 0, "no input tokens reported"


def test_integration_openai_stream() -> None:
    key = os.getenv("OPENAI_API_KEY")
    if not key:
        pytest.skip("OPENAI_API_KEY not set")
    chunks: list[str] = []
    resp = llmkit.prompt_stream(
        provider=llmkit.Provider(name="openai", api_key=key),
        request=llmkit.Request(system="Reply with only the word pong", user="ping"),
        on_chunk=chunks.append,
    )
    assert resp.text != "", "empty response text"
    assert chunks, "no chunks received"


def test_integration_openrouter() -> None:
    key = os.getenv("OPENROUTER_API_KEY")
    if not key:
        pytest.skip("OPENROUTER_API_KEY not set")
    resp = llmkit.prompt(
        provider=llmkit.Provider(name="openrouter", api_key=key),
        request=llmkit.Request(system="Reply with only the word pong", user="ping"),
    )
    assert resp.text != "", "empty response text"
    assert resp.tokens.input > 0, "no input tokens reported"


def test_integration_openrouter_stream() -> None:
    key = os.getenv("OPENROUTER_API_KEY")
    if not key:
        pytest.skip("OPENROUTER_API_KEY not set")
    chunks: list[str] = []
    resp = llmkit.prompt_stream(
        provider=llmkit.Provider(name="openrouter", api_key=key),
        request=llmkit.Request(system="Reply with only the word pong", user="ping"),
        on_chunk=chunks.append,
    )
    assert resp.text != "", "empty response text"
    assert chunks, "no chunks received"


def test_integration_perplexity() -> None:
    key = os.getenv("PERPLEXITY_API_KEY")
    if not key:
        pytest.skip("PERPLEXITY_API_KEY not set")
    resp = llmkit.prompt(
        provider=llmkit.Provider(name="perplexity", api_key=key),
        request=llmkit.Request(system="Reply with only the word pong", user="ping"),
    )
    assert resp.text != "", "empty response text"
    assert resp.tokens.input > 0, "no input tokens reported"


def test_integration_perplexity_stream() -> None:
    key = os.getenv("PERPLEXITY_API_KEY")
    if not key:
        pytest.skip("PERPLEXITY_API_KEY not set")
    chunks: list[str] = []
    resp = llmkit.prompt_stream(
        provider=llmkit.Provider(name="perplexity", api_key=key),
        request=llmkit.Request(system="Reply with only the word pong", user="ping"),
        on_chunk=chunks.append,
    )
    assert resp.text != "", "empty response text"
    assert chunks, "no chunks received"


def test_integration_qwen() -> None:
    key = os.getenv("DASHSCOPE_API_KEY")
    if not key:
        pytest.skip("DASHSCOPE_API_KEY not set")
    resp = llmkit.prompt(
        provider=llmkit.Provider(name="qwen", api_key=key),
        request=llmkit.Request(system="Reply with only the word pong", user="ping"),
    )
    assert resp.text != "", "empty response text"
    assert resp.tokens.input > 0, "no input tokens reported"


def test_integration_qwen_stream() -> None:
    key = os.getenv("DASHSCOPE_API_KEY")
    if not key:
        pytest.skip("DASHSCOPE_API_KEY not set")
    chunks: list[str] = []
    resp = llmkit.prompt_stream(
        provider=llmkit.Provider(name="qwen", api_key=key),
        request=llmkit.Request(system="Reply with only the word pong", user="ping"),
        on_chunk=chunks.append,
    )
    assert resp.text != "", "empty response text"
    assert chunks, "no chunks received"


def test_integration_sambanova() -> None:
    key = os.getenv("SAMBANOVA_API_KEY")
    if not key:
        pytest.skip("SAMBANOVA_API_KEY not set")
    resp = llmkit.prompt(
        provider=llmkit.Provider(name="sambanova", api_key=key),
        request=llmkit.Request(system="Reply with only the word pong", user="ping"),
    )
    assert resp.text != "", "empty response text"
    assert resp.tokens.input > 0, "no input tokens reported"


def test_integration_sambanova_stream() -> None:
    key = os.getenv("SAMBANOVA_API_KEY")
    if not key:
        pytest.skip("SAMBANOVA_API_KEY not set")
    chunks: list[str] = []
    resp = llmkit.prompt_stream(
        provider=llmkit.Provider(name="sambanova", api_key=key),
        request=llmkit.Request(system="Reply with only the word pong", user="ping"),
        on_chunk=chunks.append,
    )
    assert resp.text != "", "empty response text"
    assert chunks, "no chunks received"


def test_integration_together() -> None:
    key = os.getenv("TOGETHER_API_KEY")
    if not key:
        pytest.skip("TOGETHER_API_KEY not set")
    resp = llmkit.prompt(
        provider=llmkit.Provider(name="together", api_key=key),
        request=llmkit.Request(system="Reply with only the word pong", user="ping"),
    )
    assert resp.text != "", "empty response text"
    assert resp.tokens.input > 0, "no input tokens reported"


def test_integration_together_stream() -> None:
    key = os.getenv("TOGETHER_API_KEY")
    if not key:
        pytest.skip("TOGETHER_API_KEY not set")
    chunks: list[str] = []
    resp = llmkit.prompt_stream(
        provider=llmkit.Provider(name="together", api_key=key),
        request=llmkit.Request(system="Reply with only the word pong", user="ping"),
        on_chunk=chunks.append,
    )
    assert resp.text != "", "empty response text"
    assert chunks, "no chunks received"


def test_integration_yi() -> None:
    key = os.getenv("YI_API_KEY")
    if not key:
        pytest.skip("YI_API_KEY not set")
    resp = llmkit.prompt(
        provider=llmkit.Provider(name="yi", api_key=key),
        request=llmkit.Request(system="Reply with only the word pong", user="ping"),
    )
    assert resp.text != "", "empty response text"
    assert resp.tokens.input > 0, "no input tokens reported"


def test_integration_yi_stream() -> None:
    key = os.getenv("YI_API_KEY")
    if not key:
        pytest.skip("YI_API_KEY not set")
    chunks: list[str] = []
    resp = llmkit.prompt_stream(
        provider=llmkit.Provider(name="yi", api_key=key),
        request=llmkit.Request(system="Reply with only the word pong", user="ping"),
        on_chunk=chunks.append,
    )
    assert resp.text != "", "empty response text"
    assert chunks, "no chunks received"


def test_integration_zhipu() -> None:
    key = os.getenv("ZHIPU_API_KEY")
    if not key:
        pytest.skip("ZHIPU_API_KEY not set")
    resp = llmkit.prompt(
        provider=llmkit.Provider(name="zhipu", api_key=key),
        request=llmkit.Request(system="Reply with only the word pong", user="ping"),
    )
    assert resp.text != "", "empty response text"
    assert resp.tokens.input > 0, "no input tokens reported"


def test_integration_zhipu_stream() -> None:
    key = os.getenv("ZHIPU_API_KEY")
    if not key:
        pytest.skip("ZHIPU_API_KEY not set")
    chunks: list[str] = []
    resp = llmkit.prompt_stream(
        provider=llmkit.Provider(name="zhipu", api_key=key),
        request=llmkit.Request(system="Reply with only the word pong", user="ping"),
        on_chunk=chunks.append,
    )
    assert resp.text != "", "empty response text"
    assert chunks, "no chunks received"


def test_integration_anthropic_caching() -> None:
    key = os.getenv("ANTHROPIC_API_KEY")
    if not key:
        pytest.skip("ANTHROPIC_API_KEY not set")
    resp = llmkit.prompt(
        provider=llmkit.Provider(name="anthropic", api_key=key),
        request=llmkit.Request(system="Reply with only the word pong", user="ping"),
        caching=True,
    )
    assert resp.text != "", "empty response text"
    print(f"cache_read={resp.tokens.cache_read} cache_write={resp.tokens.cache_write}")


def test_integration_openai_caching() -> None:
    key = os.getenv("OPENAI_API_KEY")
    if not key:
        pytest.skip("OPENAI_API_KEY not set")
    resp = llmkit.prompt(
        provider=llmkit.Provider(name="openai", api_key=key),
        request=llmkit.Request(system="Reply with only the word pong", user="ping"),
        caching=True,
    )
    assert resp.text != "", "empty response text"
    print(f"cache_read={resp.tokens.cache_read} cache_write={resp.tokens.cache_write}")

