# Code generated by codegen/generate.py; DO NOT EDIT.

"""Typed-builder API surface introduced in ADR-009 / plan 016.

Phase 2b emits skeleton classes + raising terminals; phase 3 will
hand-write a subset of terminals against the legacy free-function
runtime in sibling files (text.py, image.py, agent.py, upload.py
in this directory). Phase 4 will move the surface into the main
llmkit module once the legacy functional API is deleted.
"""

from __future__ import annotations

import copy
from collections.abc import AsyncIterator
from dataclasses import dataclass
from typing import TYPE_CHECKING

from ..image import ImageData, MediaRef, Part
from ..providers.generated.middleware import MiddlewareFn
from ..structs import File, ImageResponse, Message, Response
from ..types import SafetySetting, Tool
from .batch import BatchHandle

if TYPE_CHECKING:
    from .agent import AgentState


@dataclass
class ProviderConfig:
    name: str
    api_key: str
    base_url: str = ""

from .agent import agent_prompt, agent_reset
from .batch import text_batch, text_submit_batch
from .image import image_generate
from .stream import text_stream
from .text import text_prompt
from .upload import upload_run

# === Text — ChatCompletion builder ===

class Text:
    """Phase 2b skeleton; chain methods clone-then-mutate via copy.copy()."""

    def __init__(self, client: "Client") -> None:
        self.client = client
        self._middleware: list[MiddlewareFn] = []
        self._caching: bool = False
        self._files: list[File] = []
        self._frequency_penalty: float | None = None
        self._history: list[Message] = []
        self._parts: list[Part] = []
        self._max_tokens: int | None = None
        self._model: str = ""
        self._presence_penalty: float | None = None
        self._raw: bool = False
        self._reasoning_effort: str = ""
        self._safety_settings: list[SafetySetting] = []
        self._schema: str = ""
        self._seed: int | None = None
        self._stop_sequences: list[str] = []
        self._system: str = ""
        self._temperature: float | None = None
        self._thinking_budget: int | None = None
        self._top_k: int | None = None
        self._top_p: float | None = None

    def add_middleware(self, *fns: MiddlewareFn) -> "Text":
        out = copy.copy(self)
        out._middleware = [*self._middleware, *fns]
        return out

    def caching(self) -> "Text":
        out = copy.copy(self)
        out._caching = True
        return out

    def file(self, id: str) -> "Text":  # ordered
        out = copy.copy(self)
        out._files = [*self._files, File(id=id)]
        return out

    def frequency_penalty(self, v: float) -> "Text":
        out = copy.copy(self)
        out._frequency_penalty = v
        return out

    def history(self, *msgs: Message) -> "Text":
        out = copy.copy(self)
        out._history = list(msgs)
        return out

    def image(self, mime: str, data: bytes) -> "Text":  # ordered
        out = copy.copy(self)
        out._parts = [*self._parts, Part(image=MediaRef(mime_type=mime, bytes=data))]
        return out

    def max_tokens(self, n: int) -> "Text":
        out = copy.copy(self)
        out._max_tokens = n
        return out

    def model(self, name: str) -> "Text":
        out = copy.copy(self)
        out._model = name
        return out

    def presence_penalty(self, v: float) -> "Text":
        out = copy.copy(self)
        out._presence_penalty = v
        return out

    def raw(self) -> "Text":
        out = copy.copy(self)
        out._raw = True
        return out

    def reasoning_effort(self, level: str) -> "Text":
        out = copy.copy(self)
        out._reasoning_effort = level
        return out

    def safety_settings(self, s: list[SafetySetting]) -> "Text":
        out = copy.copy(self)
        out._safety_settings = list(s)
        return out

    def schema(self, s: str) -> "Text":
        out = copy.copy(self)
        out._schema = s
        return out

    def seed(self, n: int) -> "Text":
        out = copy.copy(self)
        out._seed = n
        return out

    def stop_sequences(self, *seqs: str) -> "Text":
        out = copy.copy(self)
        out._stop_sequences = list(seqs)
        return out

    def system(self, s: str) -> "Text":
        out = copy.copy(self)
        out._system = s
        return out

    def temperature(self, t: float) -> "Text":
        out = copy.copy(self)
        out._temperature = t
        return out

    def text(self, s: str) -> "Text":  # ordered
        out = copy.copy(self)
        out._parts = [*self._parts, Part(text=s)]
        return out

    def thinking_budget(self, n: int) -> "Text":
        out = copy.copy(self)
        out._thinking_budget = n
        return out

    def top_k(self, n: int) -> "Text":
        out = copy.copy(self)
        out._top_k = n
        return out

    def top_p(self, v: float) -> "Text":
        out = copy.copy(self)
        out._top_p = v
        return out

    async def prompt(self, msg: str) -> Response:
        return await text_prompt(self, msg)

    def stream(self, msg: str) -> TextStream:
        return text_stream(self, msg)

    async def batch(self, *prompts: str) -> list[Response]:
        return await text_batch(self, *prompts)

    async def submit_batch(self, *prompts: str) -> BatchHandle:
        return await text_submit_batch(self, *prompts)


# === Image — ImageGeneration builder ===

class Image:
    """Phase 2b skeleton; chain methods clone-then-mutate via copy.copy()."""

    def __init__(self, client: "Client") -> None:
        self.client = client
        self._middleware: list[MiddlewareFn] = []
        self._aspect_ratio: str = ""
        self._background: str = ""
        self._count: int | None = None
        self._parts: list[Part] = []
        self._image_size: str = ""
        self._include_text: bool = False
        self._mask: MediaRef | None = None
        self._model: str = ""
        self._output_format: str = ""
        self._quality: str = ""
        self._raw: bool = False
        self._safety_filter: str = ""
        self._safety_settings: list[SafetySetting] = []
        self._extra_fields: "dict[str, Any] | None" = None

    def add_middleware(self, *fns: MiddlewareFn) -> "Image":
        out = copy.copy(self)
        out._middleware = [*self._middleware, *fns]
        return out

    def aspect_ratio(self, r: str) -> "Image":
        out = copy.copy(self)
        out._aspect_ratio = r
        return out

    def background(self, s: str) -> "Image":
        out = copy.copy(self)
        out._background = s
        return out

    def count(self, n: int) -> "Image":
        out = copy.copy(self)
        out._count = n
        return out

    def image(self, mime: str, data: bytes) -> "Image":  # ordered
        out = copy.copy(self)
        out._parts = [*self._parts, Part(image=MediaRef(mime_type=mime, bytes=data))]
        return out

    def image_size(self, s: str) -> "Image":
        out = copy.copy(self)
        out._image_size = s
        return out

    def include_text(self) -> "Image":
        out = copy.copy(self)
        out._include_text = True
        return out

    def mask(self, mime: str, data: bytes) -> "Image":
        out = copy.copy(self)
        out._mask = MediaRef(mime_type=mime, bytes=data)
        return out

    def model(self, name: str) -> "Image":
        out = copy.copy(self)
        out._model = name
        return out

    def output_format(self, s: str) -> "Image":
        out = copy.copy(self)
        out._output_format = s
        return out

    def quality(self, s: str) -> "Image":
        out = copy.copy(self)
        out._quality = s
        return out

    def raw(self) -> "Image":
        out = copy.copy(self)
        out._raw = True
        return out

    def safety_filter(self, s: str) -> "Image":
        out = copy.copy(self)
        out._safety_filter = s
        return out

    def safety_settings(self, s: list[SafetySetting]) -> "Image":
        out = copy.copy(self)
        out._safety_settings = list(s)
        return out

    def text(self, s: str) -> "Image":  # ordered
        out = copy.copy(self)
        out._parts = [*self._parts, Part(text=s)]
        return out

    def extra_fields(self, extras: "dict[str, Any]") -> "Image":
        out = copy.copy(self)
        merged = dict(self._extra_fields or {})
        merged.update(extras)
        out._extra_fields = merged
        return out

    async def generate(self, msg: str) -> ImageResponse:
        return await image_generate(self, msg)


# === Agent — ToolCalling builder ===

class Agent:
    """Phase 2b skeleton; chain methods clone-then-mutate via copy.copy()."""

    def __init__(self, client: "Client") -> None:
        self.client = client
        self._middleware: list[MiddlewareFn] = []
        self._tools: list[Tool] = []
        self._caching: bool = False
        self._frequency_penalty: float | None = None
        self._max_tokens: int | None = None
        self._max_tool_iterations: int | None = None
        self._model: str = ""
        self._presence_penalty: float | None = None
        self._raw: bool = False
        self._reasoning_effort: str = ""
        self._safety_settings: list[SafetySetting] = []
        self._seed: int | None = None
        self._stop_sequences: list[str] = []
        self._system: str = ""
        self._temperature: float | None = None
        self._thinking_budget: int | None = None
        self._top_k: int | None = None
        self._top_p: float | None = None
        self._state: "AgentState | None" = None

    def add_middleware(self, *fns: MiddlewareFn) -> "Agent":
        out = copy.copy(self)
        out._middleware = [*self._middleware, *fns]
        out._state = None
        return out

    def add_tool(self, t: Tool) -> "Agent":
        out = copy.copy(self)
        out._tools = [*self._tools, t]
        out._state = None
        return out

    def caching(self) -> "Agent":
        out = copy.copy(self)
        out._caching = True
        out._state = None
        return out

    def frequency_penalty(self, v: float) -> "Agent":
        out = copy.copy(self)
        out._frequency_penalty = v
        out._state = None
        return out

    def max_tokens(self, n: int) -> "Agent":
        out = copy.copy(self)
        out._max_tokens = n
        out._state = None
        return out

    def max_tool_iterations(self, n: int) -> "Agent":
        out = copy.copy(self)
        out._max_tool_iterations = n
        out._state = None
        return out

    def model(self, name: str) -> "Agent":
        out = copy.copy(self)
        out._model = name
        out._state = None
        return out

    def presence_penalty(self, v: float) -> "Agent":
        out = copy.copy(self)
        out._presence_penalty = v
        out._state = None
        return out

    def raw(self) -> "Agent":
        out = copy.copy(self)
        out._raw = True
        out._state = None
        return out

    def reasoning_effort(self, level: str) -> "Agent":
        out = copy.copy(self)
        out._reasoning_effort = level
        out._state = None
        return out

    def safety_settings(self, s: list[SafetySetting]) -> "Agent":
        out = copy.copy(self)
        out._safety_settings = list(s)
        out._state = None
        return out

    def seed(self, n: int) -> "Agent":
        out = copy.copy(self)
        out._seed = n
        out._state = None
        return out

    def stop_sequences(self, *seqs: str) -> "Agent":
        out = copy.copy(self)
        out._stop_sequences = list(seqs)
        out._state = None
        return out

    def system(self, s: str) -> "Agent":
        out = copy.copy(self)
        out._system = s
        out._state = None
        return out

    def temperature(self, t: float) -> "Agent":
        out = copy.copy(self)
        out._temperature = t
        out._state = None
        return out

    def thinking_budget(self, n: int) -> "Agent":
        out = copy.copy(self)
        out._thinking_budget = n
        out._state = None
        return out

    def top_k(self, n: int) -> "Agent":
        out = copy.copy(self)
        out._top_k = n
        out._state = None
        return out

    def top_p(self, v: float) -> "Agent":
        out = copy.copy(self)
        out._top_p = v
        out._state = None
        return out

    async def prompt(self, msg: str) -> Response:
        return await agent_prompt(self, msg)

    def reset(self) -> None:
        return agent_reset(self)


# === Upload — FileUpload builder ===

class Upload:
    """Phase 2b skeleton; chain methods clone-then-mutate via copy.copy()."""

    def __init__(self, client: "Client") -> None:
        self.client = client
        self._middleware: list[MiddlewareFn] = []
        self._bytes: bytes = b""
        self._filename: str = ""
        self._mime_type: str = ""
        self._path: str = ""

    def add_middleware(self, *fns: MiddlewareFn) -> "Upload":
        out = copy.copy(self)
        out._middleware = [*self._middleware, *fns]
        return out

    def bytes(self, data: bytes) -> "Upload":
        out = copy.copy(self)
        out._bytes = data
        return out

    def filename(self, name: str) -> "Upload":
        out = copy.copy(self)
        out._filename = name
        return out

    def mime_type(self, mime: str) -> "Upload":
        out = copy.copy(self)
        out._mime_type = mime
        return out

    def path(self, p: str) -> "Upload":
        out = copy.copy(self)
        out._path = p
        return out

    async def run(self) -> File:
        return await upload_run(self)


class Client:
    """Entry point for the typed-builder API. Each sub-namespace field is
    a builder prototype tied to this client; chain methods return new
    instances, the field stays constant."""

    def __init__(self, name: str, api_key: str) -> None:
        self.provider = ProviderConfig(name=name, api_key=api_key)
        self.text: Text = Text(self)
        self.image: Image = Image(self)
        self.agent: Agent = Agent(self)
        self.upload: Upload = Upload(self)
        # ADR-019: catalogue namespaces. Lazy import to avoid a
        # circular import at module load (catalogue.py needs Client)
        # — by the time __init__ runs, all modules are loaded.
        from .catalogue import Models as _Models, Providers as _Providers
        self.models: _Models = _Models(self)
        self.providers: _Providers = _Providers(self)

    def with_base_url(self, url: str) -> "Client":
        """Override the provider's default base URL. Required for
        providers whose default base URL is a template that the
        caller must substitute (e.g. Vertex AI Imagen). Returns
        the same Client for chaining."""
        self.provider.base_url = url
        return self

def new_client(name: str, api_key: str) -> Client:
    """Generic factory; per-provider helpers below are ergonomic shortcuts."""
    return Client(name, api_key)

# === Per-provider factory functions ===
def ai21(api_key: str) -> Client: return Client("ai21", api_key)
def anthropic(api_key: str) -> Client: return Client("anthropic", api_key)
def azure(api_key: str) -> Client: return Client("azure", api_key)
def bedrock(api_key: str) -> Client: return Client("bedrock", api_key)
def cerebras(api_key: str) -> Client: return Client("cerebras", api_key)
def cohere(api_key: str) -> Client: return Client("cohere", api_key)
def deepseek(api_key: str) -> Client: return Client("deepseek", api_key)
def doubao(api_key: str) -> Client: return Client("doubao", api_key)
def ernie(api_key: str) -> Client: return Client("ernie", api_key)
def fireworks(api_key: str) -> Client: return Client("fireworks", api_key)
def google(api_key: str) -> Client: return Client("google", api_key)
def grok(api_key: str) -> Client: return Client("grok", api_key)
def groq(api_key: str) -> Client: return Client("groq", api_key)
def jan(api_key: str) -> Client: return Client("jan", api_key)
def llamacpp(api_key: str) -> Client: return Client("llamacpp", api_key)
def lmstudio(api_key: str) -> Client: return Client("lmstudio", api_key)
def minimax(api_key: str) -> Client: return Client("minimax", api_key)
def mistral(api_key: str) -> Client: return Client("mistral", api_key)
def moonshot(api_key: str) -> Client: return Client("moonshot", api_key)
def ollama(api_key: str) -> Client: return Client("ollama", api_key)
def openai(api_key: str) -> Client: return Client("openai", api_key)
def openrouter(api_key: str) -> Client: return Client("openrouter", api_key)
def perplexity(api_key: str) -> Client: return Client("perplexity", api_key)
def qwen(api_key: str) -> Client: return Client("qwen", api_key)
def sambanova(api_key: str) -> Client: return Client("sambanova", api_key)
def together(api_key: str) -> Client: return Client("together", api_key)
def vertex(api_key: str) -> Client: return Client("vertex", api_key)
def vllm(api_key: str) -> Client: return Client("vllm", api_key)
def yi(api_key: str) -> Client: return Client("yi", api_key)
def zhipu(api_key: str) -> Client: return Client("zhipu", api_key)

__all__ = [
    "Client",
    "new_client",
    "ProviderConfig",
    "Text",
    "Image",
    "Agent",
    "Upload",
    "ai21",
    "anthropic",
    "azure",
    "bedrock",
    "cerebras",
    "cohere",
    "deepseek",
    "doubao",
    "ernie",
    "fireworks",
    "google",
    "grok",
    "groq",
    "jan",
    "llamacpp",
    "lmstudio",
    "minimax",
    "mistral",
    "moonshot",
    "ollama",
    "openai",
    "openrouter",
    "perplexity",
    "qwen",
    "sambanova",
    "together",
    "vertex",
    "vllm",
    "yi",
    "zhipu",
    "BatchHandle",
    "File",
    "Message",
    "Response",
    "SafetySetting",
    "Tool",
    "ImageData",
    "ImageResponse",
    "MediaRef",
    "Part",
    "MiddlewareFn",
]
