# Code generated by codegen/generate.py; DO NOT EDIT.

"""Typed-builder API surface introduced in ADR-009 / plan 016.

Phase 2b emits skeleton classes + raising terminals; phase 3 will
hand-write a subset of terminals against the legacy free-function
runtime in sibling files (text.py, image.py, agent.py, upload.py
in this directory). Phase 4 will move the surface into the main
llmkit module once the legacy functional API is deleted.
"""

from __future__ import annotations

import copy
from collections.abc import AsyncIterator
from dataclasses import dataclass, field
from typing import TYPE_CHECKING

from ..image import ImageData, MediaRef, Part
from ..providers.generated.batch import batch_config
from ..providers.generated.caching import caching_config
from ..providers.generated.image_gen import image_gen_config
from ..providers.generated.middleware import MiddlewareFn
from ..providers.generated.providers import ProviderName
from ..providers.generated.request import file_upload_config
from ..structs import File, ImageResponse, Message, MusicResponse, Response, SpeechResponse
from ..types import Capability, SafetySetting, Tool
from .agent import _agent_messages
from .batch import BatchHandle

if TYPE_CHECKING:
    from .agent import AgentState


@dataclass
class ProviderConfig:
    name: ProviderName
    api_key: str
    base_url: str = ""
    headers: dict[str, str] = field(default_factory=dict)

from .agent import agent_prompt, agent_reset
from .batch import text_batch, text_submit_batch
from .image import image_generate
from .music import music_generate
from .speech import speech_generate
from .stream import text_stream
from .text import text_prompt
from .transcription import transcription_submit, transcription_transcribe
from .upload import upload_run
from .video import video_submit

# === Text — ChatCompletion builder ===

class Text:
    """Phase 2b skeleton; chain methods clone-then-mutate via copy.copy()."""

    def __init__(self, client: "Client") -> None:
        self.client = client
        self._middleware: list[MiddlewareFn] = []
        self._caching: bool = False
        self._files: list[File] = []
        self._frequency_penalty: float | None = None
        self._history: list[Message] = []
        self._parts: list[Part] = []
        self._max_tokens: int | None = None
        self._model: str = ""
        self._presence_penalty: float | None = None
        self._raw: bool = False
        self._reasoning_effort: str = ""
        self._safety_settings: list[SafetySetting] = []
        self._schema: str = ""
        self._seed: int | None = None
        self._stop_sequences: list[str] = []
        self._system: str = ""
        self._temperature: float | None = None
        self._thinking_budget: int | None = None
        self._top_k: int | None = None
        self._top_p: float | None = None

    def add_middleware(self, *fns: MiddlewareFn) -> "Text":
        out = copy.copy(self)
        out._middleware = [*self._middleware, *fns]
        return out

    def caching(self) -> "Text":
        out = copy.copy(self)
        out._caching = True
        return out

    def file(self, id: str) -> "Text":  # ordered
        out = copy.copy(self)
        out._files = [*self._files, File(id=id)]
        return out

    def frequency_penalty(self, v: float) -> "Text":
        out = copy.copy(self)
        out._frequency_penalty = v
        return out

    def history(self, *msgs: Message) -> "Text":
        out = copy.copy(self)
        out._history = list(msgs)
        return out

    def image(self, mime: str, data: bytes) -> "Text":  # ordered
        out = copy.copy(self)
        out._parts = [*self._parts, Part(image=MediaRef(mime_type=mime, bytes=data))]
        return out

    def max_tokens(self, n: int) -> "Text":
        out = copy.copy(self)
        out._max_tokens = n
        return out

    def model(self, name: str) -> "Text":
        out = copy.copy(self)
        out._model = name
        return out

    def presence_penalty(self, v: float) -> "Text":
        out = copy.copy(self)
        out._presence_penalty = v
        return out

    def raw(self) -> "Text":
        out = copy.copy(self)
        out._raw = True
        return out

    def reasoning_effort(self, level: str) -> "Text":
        out = copy.copy(self)
        out._reasoning_effort = level
        return out

    def safety_settings(self, s: list[SafetySetting]) -> "Text":
        out = copy.copy(self)
        out._safety_settings = list(s)
        return out

    def schema(self, s: str) -> "Text":
        out = copy.copy(self)
        out._schema = s
        return out

    def seed(self, n: int) -> "Text":
        out = copy.copy(self)
        out._seed = n
        return out

    def stop_sequences(self, *seqs: str) -> "Text":
        out = copy.copy(self)
        out._stop_sequences = list(seqs)
        return out

    def system(self, s: str) -> "Text":
        out = copy.copy(self)
        out._system = s
        return out

    def temperature(self, t: float) -> "Text":
        out = copy.copy(self)
        out._temperature = t
        return out

    def text(self, s: str) -> "Text":  # ordered
        out = copy.copy(self)
        out._parts = [*self._parts, Part(text=s)]
        return out

    def thinking_budget(self, n: int) -> "Text":
        out = copy.copy(self)
        out._thinking_budget = n
        return out

    def top_k(self, n: int) -> "Text":
        out = copy.copy(self)
        out._top_k = n
        return out

    def top_p(self, v: float) -> "Text":
        out = copy.copy(self)
        out._top_p = v
        return out

    async def prompt(self, msg: str) -> Response:
        return await text_prompt(self, msg)

    def stream(self, msg: str) -> TextStream:
        return text_stream(self, msg)

    async def batch(self, *prompts: str) -> list[Response]:
        return await text_batch(self, *prompts)

    async def submit_batch(self, *prompts: str) -> BatchHandle:
        return await text_submit_batch(self, *prompts)


# === Image — ImageGeneration builder ===

class Image:
    """Phase 2b skeleton; chain methods clone-then-mutate via copy.copy()."""

    def __init__(self, client: "Client") -> None:
        self.client = client
        self._middleware: list[MiddlewareFn] = []
        self._aspect_ratio: str = ""
        self._background: str = ""
        self._count: int | None = None
        self._parts: list[Part] = []
        self._image_size: str = ""
        self._include_text: bool = False
        self._mask: MediaRef | None = None
        self._model: str = ""
        self._output_format: str = ""
        self._quality: str = ""
        self._raw: bool = False
        self._safety_filter: str = ""
        self._safety_settings: list[SafetySetting] = []
        self._extra_fields: "dict[str, Any] | None" = None

    def add_middleware(self, *fns: MiddlewareFn) -> "Image":
        out = copy.copy(self)
        out._middleware = [*self._middleware, *fns]
        return out

    def aspect_ratio(self, r: str) -> "Image":
        out = copy.copy(self)
        out._aspect_ratio = r
        return out

    def background(self, s: str) -> "Image":
        out = copy.copy(self)
        out._background = s
        return out

    def count(self, n: int) -> "Image":
        out = copy.copy(self)
        out._count = n
        return out

    def image(self, mime: str, data: bytes) -> "Image":  # ordered
        out = copy.copy(self)
        out._parts = [*self._parts, Part(image=MediaRef(mime_type=mime, bytes=data))]
        return out

    def image_size(self, s: str) -> "Image":
        out = copy.copy(self)
        out._image_size = s
        return out

    def include_text(self) -> "Image":
        out = copy.copy(self)
        out._include_text = True
        return out

    def mask(self, mime: str, data: bytes) -> "Image":
        out = copy.copy(self)
        out._mask = MediaRef(mime_type=mime, bytes=data)
        return out

    def model(self, name: str) -> "Image":
        out = copy.copy(self)
        out._model = name
        return out

    def output_format(self, s: str) -> "Image":
        out = copy.copy(self)
        out._output_format = s
        return out

    def quality(self, s: str) -> "Image":
        out = copy.copy(self)
        out._quality = s
        return out

    def raw(self) -> "Image":
        out = copy.copy(self)
        out._raw = True
        return out

    def safety_filter(self, s: str) -> "Image":
        out = copy.copy(self)
        out._safety_filter = s
        return out

    def safety_settings(self, s: list[SafetySetting]) -> "Image":
        out = copy.copy(self)
        out._safety_settings = list(s)
        return out

    def text(self, s: str) -> "Image":  # ordered
        out = copy.copy(self)
        out._parts = [*self._parts, Part(text=s)]
        return out

    def extra_fields(self, extras: "dict[str, Any]") -> "Image":
        out = copy.copy(self)
        merged = dict(self._extra_fields or {})
        merged.update(extras)
        out._extra_fields = merged
        return out

    async def generate(self, msg: str) -> ImageResponse:
        return await image_generate(self, msg)


# === Music — MusicGeneration builder ===

class Music:
    """Phase 2b skeleton; chain methods clone-then-mutate via copy.copy()."""

    def __init__(self, client: "Client") -> None:
        self.client = client
        self._middleware: list[MiddlewareFn] = []
        self._parts: list[Part] = []
        self._model: str = ""
        self._raw: bool = False

    def add_middleware(self, *fns: MiddlewareFn) -> "Music":
        out = copy.copy(self)
        out._middleware = [*self._middleware, *fns]
        return out

    def lyrics(self, s: str) -> "Music":  # ordered
        out = copy.copy(self)
        out._parts = [*self._parts, Part(lyrics=s)]
        return out

    def model(self, name: str) -> "Music":
        out = copy.copy(self)
        out._model = name
        return out

    def raw(self) -> "Music":
        out = copy.copy(self)
        out._raw = True
        return out

    def text(self, s: str) -> "Music":  # ordered
        out = copy.copy(self)
        out._parts = [*self._parts, Part(text=s)]
        return out

    async def generate(self, msg: str) -> MusicResponse:
        return await music_generate(self, msg)


# === Speech — SpeechGeneration builder ===

class Speech:
    """Phase 2b skeleton; chain methods clone-then-mutate via copy.copy()."""

    def __init__(self, client: "Client") -> None:
        self.client = client
        self._model: str = ""
        self._voice: str = ""

    def model(self, name: str) -> "Speech":
        out = copy.copy(self)
        out._model = name
        return out

    def voice(self, id: str) -> "Speech":
        out = copy.copy(self)
        out._voice = id
        return out

    async def generate(self, msg: str) -> SpeechResponse:
        return await speech_generate(self, msg)


# === Transcription — Transcription builder ===

class Transcription:
    """Phase 2b skeleton; chain methods clone-then-mutate via copy.copy()."""

    def __init__(self, client: "Client") -> None:
        self.client = client
        self._model: str = ""

    def model(self, name: str) -> "Transcription":
        out = copy.copy(self)
        out._model = name
        return out

    async def submit(self, audio_parts: list[Part]) -> TranscriptionHandle:
        return await transcription_submit(self, audio_parts)

    async def transcribe(self, audio_parts: list[Part]) -> TranscriptionResponse:
        return await transcription_transcribe(self, audio_parts)


# === Video — VideoGeneration builder ===

class Video:
    """Phase 2b skeleton; chain methods clone-then-mutate via copy.copy()."""

    def __init__(self, client: "Client") -> None:
        self.client = client
        self._middleware: list[MiddlewareFn] = []
        self._parts: list[Part] = []
        self._model: str = ""
        self._output_uri: str = ""
        self._raw: bool = False

    def add_middleware(self, *fns: MiddlewareFn) -> "Video":
        out = copy.copy(self)
        out._middleware = [*self._middleware, *fns]
        return out

    def image(self, mime: str, data: bytes) -> "Video":  # ordered
        out = copy.copy(self)
        out._parts = [*self._parts, Part(image=MediaRef(mime_type=mime, bytes=data))]
        return out

    def model(self, name: str) -> "Video":
        out = copy.copy(self)
        out._model = name
        return out

    def output_uri(self, uri: str) -> "Video":
        out = copy.copy(self)
        out._output_uri = uri
        return out

    def raw(self) -> "Video":
        out = copy.copy(self)
        out._raw = True
        return out

    def text(self, s: str) -> "Video":  # ordered
        out = copy.copy(self)
        out._parts = [*self._parts, Part(text=s)]
        return out

    async def submit(self, msg: str) -> VideoHandle:
        return await video_submit(self, msg)


# === Agent — ToolCalling builder ===

class Agent:
    """Phase 2b skeleton; chain methods clone-then-mutate via copy.copy()."""

    def __init__(self, client: "Client") -> None:
        self.client = client
        self._middleware: list[MiddlewareFn] = []
        self._tools: list[Tool] = []
        self._caching: bool = False
        self._frequency_penalty: float | None = None
        self._history: list[Message] = []
        self._max_tokens: int | None = None
        self._max_tool_iterations: int | None = None
        self._model: str = ""
        self._presence_penalty: float | None = None
        self._raw: bool = False
        self._reasoning_effort: str = ""
        self._safety_settings: list[SafetySetting] = []
        self._seed: int | None = None
        self._stop_sequences: list[str] = []
        self._system: str = ""
        self._temperature: float | None = None
        self._thinking_budget: int | None = None
        self._top_k: int | None = None
        self._top_p: float | None = None
        self._state: "AgentState | None" = None

    def add_middleware(self, *fns: MiddlewareFn) -> "Agent":
        out = copy.copy(self)
        out._middleware = [*self._middleware, *fns]
        out._state = None
        return out

    def add_tool(self, t: Tool) -> "Agent":
        out = copy.copy(self)
        out._tools = [*self._tools, t]
        out._state = None
        return out

    def caching(self) -> "Agent":
        out = copy.copy(self)
        out._caching = True
        out._state = None
        return out

    def frequency_penalty(self, v: float) -> "Agent":
        out = copy.copy(self)
        out._frequency_penalty = v
        out._state = None
        return out

    def history(self, *msgs: Message) -> "Agent":
        out = copy.copy(self)
        out._history = list(msgs)
        out._state = None
        return out

    def max_tokens(self, n: int) -> "Agent":
        out = copy.copy(self)
        out._max_tokens = n
        out._state = None
        return out

    def max_tool_iterations(self, n: int) -> "Agent":
        out = copy.copy(self)
        out._max_tool_iterations = n
        out._state = None
        return out

    def model(self, name: str) -> "Agent":
        out = copy.copy(self)
        out._model = name
        out._state = None
        return out

    def presence_penalty(self, v: float) -> "Agent":
        out = copy.copy(self)
        out._presence_penalty = v
        out._state = None
        return out

    def raw(self) -> "Agent":
        out = copy.copy(self)
        out._raw = True
        out._state = None
        return out

    def reasoning_effort(self, level: str) -> "Agent":
        out = copy.copy(self)
        out._reasoning_effort = level
        out._state = None
        return out

    def safety_settings(self, s: list[SafetySetting]) -> "Agent":
        out = copy.copy(self)
        out._safety_settings = list(s)
        out._state = None
        return out

    def seed(self, n: int) -> "Agent":
        out = copy.copy(self)
        out._seed = n
        out._state = None
        return out

    def stop_sequences(self, *seqs: str) -> "Agent":
        out = copy.copy(self)
        out._stop_sequences = list(seqs)
        out._state = None
        return out

    def system(self, s: str) -> "Agent":
        out = copy.copy(self)
        out._system = s
        out._state = None
        return out

    def temperature(self, t: float) -> "Agent":
        out = copy.copy(self)
        out._temperature = t
        out._state = None
        return out

    def thinking_budget(self, n: int) -> "Agent":
        out = copy.copy(self)
        out._thinking_budget = n
        out._state = None
        return out

    def top_k(self, n: int) -> "Agent":
        out = copy.copy(self)
        out._top_k = n
        out._state = None
        return out

    def top_p(self, v: float) -> "Agent":
        out = copy.copy(self)
        out._top_p = v
        out._state = None
        return out

    @property
    def messages(self) -> "tuple[Message, ...]":
        """Public view of the agent's accumulated history (ADR-020 HIST-004).

        Returns an empty tuple before the first ``.prompt()`` call.
        The outer tuple is immutable; each ``Message.tool_calls`` list
        and ``ToolCall`` instance is a fresh copy, so mutating them does
        NOT affect the agent. The narrow aliasing risk is the
        ``ToolCall.input`` dict reference, which is shared with the
        agent's internal state — replacing it on a returned ``Message``
        is safe, but in-place dict mutation corrupts the agent. Treat
        the inner ``input`` mapping as read-only.
        """
        if self._state is None:
            return ()
        return _agent_messages(self._state.agent)

    def save(self) -> bytes:
        """Serialize the agent's accumulated history into the canonical
        wire format (ADR-023 STAB-012). Sugar over
        ``save_history(bot.messages)``."""
        from ..wire import save_history
        return save_history(list(self.messages))

    def load(self, data: "bytes | str") -> "Agent":
        """Decode a wire document and replace the chain's history
        list, returning a fresh fork with cleared runtime state
        (ADR-023 STAB-012). Raises UnsupportedWireVersionError,
        MissingWireVersionError, or UnknownWireKeyError on a
        non-conforming document."""
        from ..wire import load_history
        out = copy.copy(self)
        out._history = load_history(data)
        out._state = None
        return out

    async def prompt(self, msg: str) -> Response:
        return await agent_prompt(self, msg)

    def reset(self) -> None:
        return agent_reset(self)


# === Upload — FileUpload builder ===

class Upload:
    """Phase 2b skeleton; chain methods clone-then-mutate via copy.copy()."""

    def __init__(self, client: "Client") -> None:
        self.client = client
        self._middleware: list[MiddlewareFn] = []
        self._bytes: bytes = b""
        self._filename: str = ""
        self._mime_type: str = ""
        self._path: str = ""

    def add_middleware(self, *fns: MiddlewareFn) -> "Upload":
        out = copy.copy(self)
        out._middleware = [*self._middleware, *fns]
        return out

    def bytes(self, data: bytes) -> "Upload":
        out = copy.copy(self)
        out._bytes = data
        return out

    def filename(self, name: str) -> "Upload":
        out = copy.copy(self)
        out._filename = name
        return out

    def mime_type(self, mime: str) -> "Upload":
        out = copy.copy(self)
        out._mime_type = mime
        return out

    def path(self, p: str) -> "Upload":
        out = copy.copy(self)
        out._path = p
        return out

    async def run(self) -> File:
        return await upload_run(self)


class Client:
    """Entry point for the typed-builder API. Each sub-namespace field is
    a builder prototype tied to this client; chain methods return new
    instances, the field stays constant."""

    def __init__(self, name: ProviderName, api_key: str) -> None:
        self.provider = ProviderConfig(name=name, api_key=api_key)
        self.text: Text = Text(self)
        self.image: Image = Image(self)
        self.music: Music = Music(self)
        self.speech: Speech = Speech(self)
        self.transcription: Transcription = Transcription(self)
        self.video: Video = Video(self)
        self.agent: Agent = Agent(self)
        self.upload: Upload = Upload(self)
        # ADR-019: catalogue namespaces. Lazy import to avoid a
        # circular import at module load (catalogue.py needs Client)
        # — by the time __init__ runs, all modules are loaded.
        from .catalogue import Models as _Models, Providers as _Providers
        self.models: _Models = _Models(self)
        self.providers: _Providers = _Providers(self)

    def add_header(self, name: str, value: str) -> "Client":
        """Attach a custom HTTP header to every request for this client; calls accumulate. Applied before the provider auth header, so a gateway header (e.g. cf-aig-authorization) rides alongside the provider key. Returns the same Client."""
        self.provider.headers[name] = value
        return self

    def base_url(self, url: str) -> "Client":
        """Override the provider's default base URL. Required for providers whose default base URL is a template the caller must substitute (e.g. Vertex AI Imagen) and to point an OpenAI-compatible provider or gateway at a self-hosted endpoint. Returns the same Client."""
        self.provider.base_url = url
        return self

    def supports(self, cap: str) -> bool:
        """True iff an explicit request for ``cap`` (a Capability
        value) will not hard-fail pre-flight on this client's
        provider (ADR-030). Gated arms dispatch the same generated
        lookups as the strict validation paths; capabilities with
        no provider-level gate return True. Says nothing about
        per-model or per-option rejections — use the catalogue's
        ModelInfo.capabilities for model-level facts. Sync, no IO."""
        gated = (
            Capability.CACHING,
            Capability.BATCHING,
            Capability.FILE_UPLOAD,
            Capability.IMAGE_GENERATION,
        )
        if cap not in gated:
            return True
        try:
            pn = ProviderName(self.provider.name)
        except ValueError:
            # Unknown provider: the strict gate would hard-fail too.
            return False
        if cap == Capability.CACHING:
            return caching_config(pn) is not None
        if cap == Capability.BATCHING:
            return batch_config(pn) is not None
        if cap == Capability.FILE_UPLOAD:
            return file_upload_config(pn) is not None
        return image_gen_config(pn) is not None

def new_client(name: ProviderName, api_key: str) -> Client:
    """Generic factory taking the typed ProviderName identity (ADR-040);
    per-provider helpers below are ergonomic shortcuts. A config slug crosses
    in via ProviderName(slug)."""
    return Client(name, api_key)

# === Per-provider factory functions ===
def ai21(api_key: str) -> Client: return Client(ProviderName.AI21, api_key)
def anthropic(api_key: str) -> Client: return Client(ProviderName.ANTHROPIC, api_key)
def assemblyai(api_key: str) -> Client: return Client(ProviderName.ASSEMBLYAI, api_key)
def azure(api_key: str) -> Client: return Client(ProviderName.AZURE, api_key)
def bedrock(api_key: str) -> Client: return Client(ProviderName.BEDROCK, api_key)
def cerebras(api_key: str) -> Client: return Client(ProviderName.CEREBRAS, api_key)
def cohere(api_key: str) -> Client: return Client(ProviderName.COHERE, api_key)
def deepseek(api_key: str) -> Client: return Client(ProviderName.DEEPSEEK, api_key)
def doubao(api_key: str) -> Client: return Client(ProviderName.DOUBAO, api_key)
def ernie(api_key: str) -> Client: return Client(ProviderName.ERNIE, api_key)
def fireworks(api_key: str) -> Client: return Client(ProviderName.FIREWORKS, api_key)
def google(api_key: str) -> Client: return Client(ProviderName.GOOGLE, api_key)
def grok(api_key: str) -> Client: return Client(ProviderName.GROK, api_key)
def groq(api_key: str) -> Client: return Client(ProviderName.GROQ, api_key)
def inworld(api_key: str) -> Client: return Client(ProviderName.INWORLD, api_key)
def jan(api_key: str) -> Client: return Client(ProviderName.JAN, api_key)
def llamacpp(api_key: str) -> Client: return Client(ProviderName.LLAMACPP, api_key)
def lmstudio(api_key: str) -> Client: return Client(ProviderName.LMSTUDIO, api_key)
def minimax(api_key: str) -> Client: return Client(ProviderName.MINIMAX, api_key)
def mistral(api_key: str) -> Client: return Client(ProviderName.MISTRAL, api_key)
def moonshot(api_key: str) -> Client: return Client(ProviderName.MOONSHOT, api_key)
def ollama(api_key: str) -> Client: return Client(ProviderName.OLLAMA, api_key)
def openai(api_key: str) -> Client: return Client(ProviderName.OPENAI, api_key)
def openrouter(api_key: str) -> Client: return Client(ProviderName.OPENROUTER, api_key)
def perplexity(api_key: str) -> Client: return Client(ProviderName.PERPLEXITY, api_key)
def pixverse(api_key: str) -> Client: return Client(ProviderName.PIXVERSE, api_key)
def qwen(api_key: str) -> Client: return Client(ProviderName.QWEN, api_key)
def recraft(api_key: str) -> Client: return Client(ProviderName.RECRAFT, api_key)
def sambanova(api_key: str) -> Client: return Client(ProviderName.SAMBANOVA, api_key)
def together(api_key: str) -> Client: return Client(ProviderName.TOGETHER, api_key)
def vertex(api_key: str) -> Client: return Client(ProviderName.VERTEX, api_key)
def vidu(api_key: str) -> Client: return Client(ProviderName.VIDU, api_key)
def vllm(api_key: str) -> Client: return Client(ProviderName.VLLM, api_key)
def workersai(api_key: str) -> Client: return Client(ProviderName.WORKERSAI, api_key)
def yi(api_key: str) -> Client: return Client(ProviderName.YI, api_key)
def zhipu(api_key: str) -> Client: return Client(ProviderName.ZHIPU, api_key)

__all__ = [
    "Client",
    "new_client",
    "ProviderConfig",
    "Text",
    "Image",
    "Music",
    "Speech",
    "Transcription",
    "Video",
    "Agent",
    "Upload",
    "ai21",
    "anthropic",
    "assemblyai",
    "azure",
    "bedrock",
    "cerebras",
    "cohere",
    "deepseek",
    "doubao",
    "ernie",
    "fireworks",
    "google",
    "grok",
    "groq",
    "inworld",
    "jan",
    "llamacpp",
    "lmstudio",
    "minimax",
    "mistral",
    "moonshot",
    "ollama",
    "openai",
    "openrouter",
    "perplexity",
    "pixverse",
    "qwen",
    "recraft",
    "sambanova",
    "together",
    "vertex",
    "vidu",
    "vllm",
    "workersai",
    "yi",
    "zhipu",
    "BatchHandle",
    "File",
    "Message",
    "Response",
    "SafetySetting",
    "Tool",
    "ImageData",
    "ImageResponse",
    "MusicResponse",
    "SpeechResponse",
    "MediaRef",
    "Part",
    "MiddlewareFn",
]
