# Code generated by codegen/generate.py; DO NOT EDIT.

"""Catalogue builder classes (ADR-019). Chain methods are immutable; the
HTTP-touching terminals delegate to hand-coded runtime in ../models.py.
The providers-namespace runtime lives in the same module — Python's
package layout reserves `llmkit.providers` as the generated subpackage,
so the hand-coded mirror of Go's go/providers.go folds into models.py.

Module-level imports from ..models are safe: ..models references
.builders.catalogue only at function scope (inside catalogue_run_live).
The cycle is broken on that side, not this one."""

from __future__ import annotations

import copy
from typing import TYPE_CHECKING

from ..models import (
    catalogue_filter,
    catalogue_lookup,
    catalogue_providers_list,
    catalogue_run_get,
    catalogue_run_list,
    catalogue_run_live,
)
from ..providers.generated.provider_info import ProviderInfo
from ..structs import LiveResult, ModelInfo
from ..types import Capability, Provider

if TYPE_CHECKING:
    from . import Client


class Models:
    """Models is the catalogue builder. Chain methods are immutable;
    list/get walk the compiled-in slice synchronously, live() fans
    out HTTP across configured providers, provider(p) returns
    ScopedModels."""

    def __init__(self, client: "Client", cap_filter: Capability | None = None) -> None:
        self.client = client
        self.cap_filter = cap_filter

    def with_capability(self, c: Capability) -> "Models":
        """Filter the catalogue to models whose ontology-derived capabilities
        list contains c. Composes with list / live / provider(p).list."""
        out = copy.copy(self)
        out.cap_filter = c
        return out

    def provider(self, p: Provider) -> "ScopedModels":
        """Scope the catalogue to a single provider; returns ScopedModels on
        which raw(), list(), and get(id) are reachable."""
        return ScopedModels(self.client, p, self.cap_filter)

    def list(self) -> list[ModelInfo]:
        """Returns the compiled-in catalogue, filtered by with_capability
        when set. Sync, no IO."""
        return catalogue_filter(self.cap_filter)

    def get(self, id: str) -> ModelInfo | None:
        """Returns a compiled-in model by id or None when no entry matches."""
        return catalogue_lookup(id)

    async def live(self) -> LiveResult:
        """Fan out HTTP across configured providers and return an aggregated
        LiveResult. with_capability composes post-fetch."""
        return await catalogue_run_live(self)


class ScopedModels:
    """ScopedModels is the single-provider live-catalogue sub-builder.
    Reached via Models.provider(p). raw() opts into populating
    ModelInfo.raw per ADR-014."""

    def __init__(
        self,
        client: "Client",
        target: Provider,
        cap_filter: Capability | None = None,
        raw_flag: bool = False,
    ) -> None:
        self.client = client
        self.target = target
        self.cap_filter = cap_filter
        self.raw_flag = raw_flag

    def raw(self) -> "ScopedModels":
        out = copy.copy(self)
        out.raw_flag = True
        return out

    async def list(self) -> list[ModelInfo]:
        return await catalogue_run_list(self)

    async def get(self, id: str) -> ModelInfo:
        return await catalogue_run_get(self, id)


class Providers:
    """Providers is the providers-namespace prototype. list() returns the
    providers with both credentials configured and llm:hasModelsEndpoint
    declared, as secret-free ProviderInfo (ADR-040 PSR-005). The static
    roster of every supported provider is the `llmkit.providers` namespace
    (providers.list())."""

    def __init__(self, client: "Client") -> None:
        self.client = client

    def list(self) -> list[ProviderInfo]:
        return catalogue_providers_list(self.client)
