# Code generated by codegen/generate.py; DO NOT EDIT.

"""Catalogue data (ADR-019). Compiled-in model slice + per-model capability
lookup + per-provider live-endpoint config. Walked at runtime by the
Models / ScopedModels / Providers classes (generated in builders/catalogue.py)
and the hand-coded runtime in models.py / providers.py."""

from __future__ import annotations

from dataclasses import dataclass

from .structs import ModelInfo
from .types import Capability, Provider


# Compiled-in catalogue, sorted by (provider, id). Walked by
# Models.list() and Models.get(id).
compiled_in_models: list[ModelInfo] = [
    ModelInfo(id="claude-haiku-4-5-20251001", provider=Provider(name="anthropic", api_key=""), capabilities=[Capability.CHAT_COMPLETION, Capability.TOOL_CALLING], display_name="Claude Haiku 4.5", context_window=200000, max_output=64000),
    ModelInfo(id="claude-opus-4-5-20251101", provider=Provider(name="anthropic", api_key=""), capabilities=[Capability.CHAT_COMPLETION, Capability.TOOL_CALLING], display_name="Claude Opus 4.5", context_window=200000, max_output=64000),
    ModelInfo(id="claude-opus-4-6", provider=Provider(name="anthropic", api_key=""), capabilities=[Capability.CHAT_COMPLETION, Capability.TOOL_CALLING], display_name="Claude Opus 4.6", context_window=1000000, max_output=128000),
    ModelInfo(id="claude-opus-4-7", provider=Provider(name="anthropic", api_key=""), capabilities=[Capability.CHAT_COMPLETION, Capability.TOOL_CALLING], display_name="Claude Opus 4.7", context_window=1000000, max_output=128000),
    ModelInfo(id="claude-sonnet-4-5-20250929", provider=Provider(name="anthropic", api_key=""), capabilities=[Capability.CHAT_COMPLETION, Capability.TOOL_CALLING], display_name="Claude Sonnet 4.5", context_window=1000000, max_output=64000),
    ModelInfo(id="claude-sonnet-4-6", provider=Provider(name="anthropic", api_key=""), capabilities=[Capability.CHAT_COMPLETION, Capability.TOOL_CALLING], display_name="Claude Sonnet 4.6", context_window=1000000, max_output=128000),
    ModelInfo(id="gemini-2.5-flash", provider=Provider(name="google", api_key=""), capabilities=[Capability.CHAT_COMPLETION, Capability.REASONING, Capability.TOOL_CALLING], display_name="Gemini 2.5 Flash", description="Stable version of Gemini 2.5 Flash", context_window=1048576, max_output=65536),
    ModelInfo(id="gemini-2.5-flash-lite", provider=Provider(name="google", api_key=""), capabilities=[Capability.CHAT_COMPLETION, Capability.TOOL_CALLING], display_name="Gemini 2.5 Flash-Lite", description="Stable version of Gemini 2.5 Flash-Lite", context_window=1048576, max_output=65536),
    ModelInfo(id="gemini-2.5-pro", provider=Provider(name="google", api_key=""), capabilities=[Capability.CHAT_COMPLETION, Capability.REASONING, Capability.TOOL_CALLING], display_name="Gemini 2.5 Pro", description="Stable release of Gemini 2.5 Pro", context_window=1048576, max_output=65536),
    ModelInfo(id="gemini-3-pro-image-preview", provider=Provider(name="google", api_key=""), capabilities=[Capability.IMAGE_GENERATION], display_name="Nano Banana Pro", description="Gemini 3 Pro Image Preview", context_window=131072, max_output=32768),
    ModelInfo(id="gemini-3-pro-preview", provider=Provider(name="google", api_key=""), capabilities=[Capability.CHAT_COMPLETION, Capability.REASONING, Capability.TOOL_CALLING], display_name="Gemini 3 Pro Preview", description="Gemini 3 Pro Preview", context_window=1048576, max_output=65536),
    ModelInfo(id="gemini-3.1-flash-image-preview", provider=Provider(name="google", api_key=""), capabilities=[Capability.IMAGE_GENERATION], display_name="Nano Banana 2", description="Gemini 3.1 Flash Image Preview", context_window=65536, max_output=65536),
    ModelInfo(id="gpt-4o", provider=Provider(name="openai", api_key=""), capabilities=[Capability.CHAT_COMPLETION, Capability.TOOL_CALLING]),
    ModelInfo(id="gpt-4o-mini", provider=Provider(name="openai", api_key=""), capabilities=[Capability.CHAT_COMPLETION, Capability.TOOL_CALLING]),
    ModelInfo(id="gpt-5", provider=Provider(name="openai", api_key=""), capabilities=[Capability.CHAT_COMPLETION, Capability.REASONING, Capability.TOOL_CALLING]),
    ModelInfo(id="gpt-image-1", provider=Provider(name="openai", api_key=""), capabilities=[Capability.IMAGE_GENERATION]),
    ModelInfo(id="o1", provider=Provider(name="openai", api_key=""), capabilities=[Capability.CHAT_COMPLETION, Capability.REASONING]),
    ModelInfo(id="o3", provider=Provider(name="openai", api_key=""), capabilities=[Capability.CHAT_COMPLETION, Capability.REASONING, Capability.TOOL_CALLING]),
    ModelInfo(id="o4-mini", provider=Provider(name="openai", api_key=""), capabilities=[Capability.CHAT_COMPLETION, Capability.REASONING, Capability.TOOL_CALLING]),
]

# (provider name, model id) -> capabilities — consulted by live-path
# parsers to enrich ModelInfo records with capability data the wire
# never carries. Unknown pairs return None.
ontology_capabilities: dict[str, dict[str, list[Capability]]] = {
    "anthropic": {
        "claude-haiku-4-5-20251001": [Capability.CHAT_COMPLETION, Capability.TOOL_CALLING],
        "claude-opus-4-5-20251101": [Capability.CHAT_COMPLETION, Capability.TOOL_CALLING],
        "claude-opus-4-6": [Capability.CHAT_COMPLETION, Capability.TOOL_CALLING],
        "claude-opus-4-7": [Capability.CHAT_COMPLETION, Capability.TOOL_CALLING],
        "claude-sonnet-4-5-20250929": [Capability.CHAT_COMPLETION, Capability.TOOL_CALLING],
        "claude-sonnet-4-6": [Capability.CHAT_COMPLETION, Capability.TOOL_CALLING],
    },
    "google": {
        "gemini-2.5-flash": [Capability.CHAT_COMPLETION, Capability.REASONING, Capability.TOOL_CALLING],
        "gemini-2.5-flash-lite": [Capability.CHAT_COMPLETION, Capability.TOOL_CALLING],
        "gemini-2.5-pro": [Capability.CHAT_COMPLETION, Capability.REASONING, Capability.TOOL_CALLING],
        "gemini-3-pro-image-preview": [Capability.IMAGE_GENERATION],
        "gemini-3-pro-preview": [Capability.CHAT_COMPLETION, Capability.REASONING, Capability.TOOL_CALLING],
        "gemini-3.1-flash-image-preview": [Capability.IMAGE_GENERATION],
    },
    "openai": {
        "gpt-4o": [Capability.CHAT_COMPLETION, Capability.TOOL_CALLING],
        "gpt-4o-mini": [Capability.CHAT_COMPLETION, Capability.TOOL_CALLING],
        "gpt-5": [Capability.CHAT_COMPLETION, Capability.REASONING, Capability.TOOL_CALLING],
        "gpt-image-1": [Capability.IMAGE_GENERATION],
        "o1": [Capability.CHAT_COMPLETION, Capability.REASONING],
        "o3": [Capability.CHAT_COMPLETION, Capability.REASONING, Capability.TOOL_CALLING],
        "o4-mini": [Capability.CHAT_COMPLETION, Capability.REASONING, Capability.TOOL_CALLING],
    },
}

# Per-provider live-catalogue endpoint config (ADR-019). Providers
# without a live endpoint are absent; ScopedModels.list raises
# ErrModelsNotSupported for those.
@dataclass
class CatalogueConfig:
    endpoint: str
    pagination: str
    spec_url: str = ""
    spec_format: str = ""

catalogue_by_provider: dict[str, CatalogueConfig] = {
    "anthropic": CatalogueConfig(endpoint="/v1/models", pagination="CursorByLastID", spec_url="https://github.com/anthropics/anthropic-sdk-typescript/blob/main/api.md", spec_format="OpenAPI3"),
    "google": CatalogueConfig(endpoint="/v1beta/models", pagination="CursorOpaqueToken", spec_url="https://generativelanguage.googleapis.com/$discovery/rest?version=v1beta", spec_format="GoogleDiscovery"),
    "openai": CatalogueConfig(endpoint="/v1/models", pagination="PaginationNone", spec_url="https://github.com/openai/openai-openapi/blob/master/openapi.yaml", spec_format="OpenAPI3"),
}
